// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Buffer.proto

package com.dj.protobuf.buffer;

public interface MonthCardReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.MonthCardReq)
    com.google.protobuf.MessageOrBuilder {
}
