// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Buffer.proto

package com.dj.protobuf.buffer;

public interface MonthCardDrawRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.MonthCardDrawRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  boolean hasErrorID();
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID();

  /**
   * <code>optional .Protocols.MonthCardDrawReq req = 2;</code>
   */
  boolean hasReq();
  /**
   * <code>optional .Protocols.MonthCardDrawReq req = 2;</code>
   */
  com.dj.protobuf.buffer.MonthCardDrawReq getReq();
  /**
   * <code>optional .Protocols.MonthCardDrawReq req = 2;</code>
   */
  com.dj.protobuf.buffer.MonthCardDrawReqOrBuilder getReqOrBuilder();
}
