// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Park.proto

package com.dj.protobuf.park;

public interface ParkPlaceTreeRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.ParkPlaceTreeRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  boolean hasErrorID();
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID();

  /**
   * <code>optional .Protocols.ParkPlaceTreeReq req = 2;</code>
   */
  boolean hasReq();
  /**
   * <code>optional .Protocols.ParkPlaceTreeReq req = 2;</code>
   */
  com.dj.protobuf.park.ParkPlaceTreeReq getReq();
  /**
   * <code>optional .Protocols.ParkPlaceTreeReq req = 2;</code>
   */
  com.dj.protobuf.park.ParkPlaceTreeReqOrBuilder getReqOrBuilder();
}
