// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Park.proto

package com.dj.protobuf.park;

public interface ParkCellNtfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.ParkCellNtf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Protocols.ParkCell cells = 1;</code>
   */
  java.util.List<com.dj.protobuf.park.ParkCell> 
      getCellsList();
  /**
   * <code>repeated .Protocols.ParkCell cells = 1;</code>
   */
  com.dj.protobuf.park.ParkCell getCells(int index);
  /**
   * <code>repeated .Protocols.ParkCell cells = 1;</code>
   */
  int getCellsCount();
  /**
   * <code>repeated .Protocols.ParkCell cells = 1;</code>
   */
  java.util.List<? extends com.dj.protobuf.park.ParkCellOrBuilder> 
      getCellsOrBuilderList();
  /**
   * <code>repeated .Protocols.ParkCell cells = 1;</code>
   */
  com.dj.protobuf.park.ParkCellOrBuilder getCellsOrBuilder(
      int index);
}
