// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.dj.protobuf.login;

public interface PlayerLoginInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.PlayerLoginInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Protocols.PlayerAttrClientNtf ntf = 10;</code>
   */
  boolean hasNtf();
  /**
   * <code>optional .Protocols.PlayerAttrClientNtf ntf = 10;</code>
   */
  com.dj.protobuf.login.PlayerAttrClientNtf getNtf();
  /**
   * <code>optional .Protocols.PlayerAttrClientNtf ntf = 10;</code>
   */
  com.dj.protobuf.login.PlayerAttrClientNtfOrBuilder getNtfOrBuilder();
}
