// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MeetEgg.proto

package com.dj.protobuf.meetEgg;

public interface MeetEggPauseStartReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.MeetEggPauseStartReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1暂停， 0开始
   * </pre>
   *
   * <code>optional int32 state = 1;</code>
   */
  boolean hasState();
  /**
   * <pre>
   * 1暂停， 0开始
   * </pre>
   *
   * <code>optional int32 state = 1;</code>
   */
  int getState();
}
