// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package com.dj.protobuf.guild;

/**
 * Protobuf enum {@code Protocols.EGuildOperationType}
 */
public enum EGuildOperationType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *加入公会
   * </pre>
   *
   * <code>AttendGuild = 1;</code>
   */
  AttendGuild(1),
  /**
   * <pre>
   *退出公会
   * </pre>
   *
   * <code>QuitGuild = 2;</code>
   */
  QuitGuild(2),
  /**
   * <pre>
   *已经存在公会
   * </pre>
   *
   * <code>ExistGuild = 3;</code>
   */
  ExistGuild(3),
  ;

  /**
   * <pre>
   *加入公会
   * </pre>
   *
   * <code>AttendGuild = 1;</code>
   */
  public static final int AttendGuild_VALUE = 1;
  /**
   * <pre>
   *退出公会
   * </pre>
   *
   * <code>QuitGuild = 2;</code>
   */
  public static final int QuitGuild_VALUE = 2;
  /**
   * <pre>
   *已经存在公会
   * </pre>
   *
   * <code>ExistGuild = 3;</code>
   */
  public static final int ExistGuild_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EGuildOperationType valueOf(int value) {
    return forNumber(value);
  }

  public static EGuildOperationType forNumber(int value) {
    switch (value) {
      case 1: return AttendGuild;
      case 2: return QuitGuild;
      case 3: return ExistGuild;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EGuildOperationType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EGuildOperationType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EGuildOperationType>() {
          public EGuildOperationType findValueByNumber(int number) {
            return EGuildOperationType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dj.protobuf.guild.Guild.getDescriptor()
        .getEnumTypes().get(2);
  }

  private static final EGuildOperationType[] VALUES = values();

  public static EGuildOperationType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EGuildOperationType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Protocols.EGuildOperationType)
}

