// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package com.dj.protobuf.guild;

/**
 * <pre>
 *&#47; &lt;summary&gt;
 * / 踢出公会响应
 * / &lt;/summary&gt;
 * </pre>
 *
 * Protobuf type {@code Protocols.GuildKickRsp}
 */
public  final class GuildKickRsp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.GuildKickRsp)
    GuildKickRspOrBuilder {
  // Use GuildKickRsp.newBuilder() to construct.
  private GuildKickRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GuildKickRsp() {
    errorID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GuildKickRsp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.dj.protobuf.ErrorIDOuterClass.ErrorID value = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              errorID_ = rawValue;
            }
            break;
          }
          case 18: {
            com.dj.protobuf.guild.GuildBaseInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = guildBaseInfo_.toBuilder();
            }
            guildBaseInfo_ = input.readMessage(com.dj.protobuf.guild.GuildBaseInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(guildBaseInfo_);
              guildBaseInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            com.dj.protobuf.guild.GuildKickReq.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = req_.toBuilder();
            }
            req_ = input.readMessage(com.dj.protobuf.guild.GuildKickReq.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(req_);
              req_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.guild.Guild.internal_static_Protocols_GuildKickRsp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.guild.Guild.internal_static_Protocols_GuildKickRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.guild.GuildKickRsp.class, com.dj.protobuf.guild.GuildKickRsp.Builder.class);
  }

  private int bitField0_;
  public static final int ERRORID_FIELD_NUMBER = 1;
  private int errorID_;
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public boolean hasErrorID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
    com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
    return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
  }

  public static final int GUILDBASEINFO_FIELD_NUMBER = 2;
  private com.dj.protobuf.guild.GuildBaseInfo guildBaseInfo_;
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 更新后的基本信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
   */
  public boolean hasGuildBaseInfo() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 更新后的基本信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
   */
  public com.dj.protobuf.guild.GuildBaseInfo getGuildBaseInfo() {
    return guildBaseInfo_ == null ? com.dj.protobuf.guild.GuildBaseInfo.getDefaultInstance() : guildBaseInfo_;
  }
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 更新后的基本信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
   */
  public com.dj.protobuf.guild.GuildBaseInfoOrBuilder getGuildBaseInfoOrBuilder() {
    return guildBaseInfo_ == null ? com.dj.protobuf.guild.GuildBaseInfo.getDefaultInstance() : guildBaseInfo_;
  }

  public static final int REQ_FIELD_NUMBER = 3;
  private com.dj.protobuf.guild.GuildKickReq req_;
  /**
   * <code>optional .Protocols.GuildKickReq req = 3;</code>
   */
  public boolean hasReq() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .Protocols.GuildKickReq req = 3;</code>
   */
  public com.dj.protobuf.guild.GuildKickReq getReq() {
    return req_ == null ? com.dj.protobuf.guild.GuildKickReq.getDefaultInstance() : req_;
  }
  /**
   * <code>optional .Protocols.GuildKickReq req = 3;</code>
   */
  public com.dj.protobuf.guild.GuildKickReqOrBuilder getReqOrBuilder() {
    return req_ == null ? com.dj.protobuf.guild.GuildKickReq.getDefaultInstance() : req_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, errorID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getGuildBaseInfo());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getReq());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errorID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGuildBaseInfo());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReq());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.guild.GuildKickRsp)) {
      return super.equals(obj);
    }
    com.dj.protobuf.guild.GuildKickRsp other = (com.dj.protobuf.guild.GuildKickRsp) obj;

    boolean result = true;
    result = result && (hasErrorID() == other.hasErrorID());
    if (hasErrorID()) {
      result = result && errorID_ == other.errorID_;
    }
    result = result && (hasGuildBaseInfo() == other.hasGuildBaseInfo());
    if (hasGuildBaseInfo()) {
      result = result && getGuildBaseInfo()
          .equals(other.getGuildBaseInfo());
    }
    result = result && (hasReq() == other.hasReq());
    if (hasReq()) {
      result = result && getReq()
          .equals(other.getReq());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasErrorID()) {
      hash = (37 * hash) + ERRORID_FIELD_NUMBER;
      hash = (53 * hash) + errorID_;
    }
    if (hasGuildBaseInfo()) {
      hash = (37 * hash) + GUILDBASEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getGuildBaseInfo().hashCode();
    }
    if (hasReq()) {
      hash = (37 * hash) + REQ_FIELD_NUMBER;
      hash = (53 * hash) + getReq().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guild.GuildKickRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.guild.GuildKickRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 踢出公会响应
   * / &lt;/summary&gt;
   * </pre>
   *
   * Protobuf type {@code Protocols.GuildKickRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.GuildKickRsp)
      com.dj.protobuf.guild.GuildKickRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.guild.Guild.internal_static_Protocols_GuildKickRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.guild.Guild.internal_static_Protocols_GuildKickRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.guild.GuildKickRsp.class, com.dj.protobuf.guild.GuildKickRsp.Builder.class);
    }

    // Construct using com.dj.protobuf.guild.GuildKickRsp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGuildBaseInfoFieldBuilder();
        getReqFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      errorID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (guildBaseInfoBuilder_ == null) {
        guildBaseInfo_ = null;
      } else {
        guildBaseInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (reqBuilder_ == null) {
        req_ = null;
      } else {
        reqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.guild.Guild.internal_static_Protocols_GuildKickRsp_descriptor;
    }

    public com.dj.protobuf.guild.GuildKickRsp getDefaultInstanceForType() {
      return com.dj.protobuf.guild.GuildKickRsp.getDefaultInstance();
    }

    public com.dj.protobuf.guild.GuildKickRsp build() {
      com.dj.protobuf.guild.GuildKickRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.guild.GuildKickRsp buildPartial() {
      com.dj.protobuf.guild.GuildKickRsp result = new com.dj.protobuf.guild.GuildKickRsp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.errorID_ = errorID_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (guildBaseInfoBuilder_ == null) {
        result.guildBaseInfo_ = guildBaseInfo_;
      } else {
        result.guildBaseInfo_ = guildBaseInfoBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (reqBuilder_ == null) {
        result.req_ = req_;
      } else {
        result.req_ = reqBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.guild.GuildKickRsp) {
        return mergeFrom((com.dj.protobuf.guild.GuildKickRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.guild.GuildKickRsp other) {
      if (other == com.dj.protobuf.guild.GuildKickRsp.getDefaultInstance()) return this;
      if (other.hasErrorID()) {
        setErrorID(other.getErrorID());
      }
      if (other.hasGuildBaseInfo()) {
        mergeGuildBaseInfo(other.getGuildBaseInfo());
      }
      if (other.hasReq()) {
        mergeReq(other.getReq());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.guild.GuildKickRsp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.guild.GuildKickRsp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorID_ = 0;
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public boolean hasErrorID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
      com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
      return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder setErrorID(com.dj.protobuf.ErrorIDOuterClass.ErrorID value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      errorID_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder clearErrorID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorID_ = 0;
      onChanged();
      return this;
    }

    private com.dj.protobuf.guild.GuildBaseInfo guildBaseInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.guild.GuildBaseInfo, com.dj.protobuf.guild.GuildBaseInfo.Builder, com.dj.protobuf.guild.GuildBaseInfoOrBuilder> guildBaseInfoBuilder_;
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public boolean hasGuildBaseInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public com.dj.protobuf.guild.GuildBaseInfo getGuildBaseInfo() {
      if (guildBaseInfoBuilder_ == null) {
        return guildBaseInfo_ == null ? com.dj.protobuf.guild.GuildBaseInfo.getDefaultInstance() : guildBaseInfo_;
      } else {
        return guildBaseInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public Builder setGuildBaseInfo(com.dj.protobuf.guild.GuildBaseInfo value) {
      if (guildBaseInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        guildBaseInfo_ = value;
        onChanged();
      } else {
        guildBaseInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public Builder setGuildBaseInfo(
        com.dj.protobuf.guild.GuildBaseInfo.Builder builderForValue) {
      if (guildBaseInfoBuilder_ == null) {
        guildBaseInfo_ = builderForValue.build();
        onChanged();
      } else {
        guildBaseInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public Builder mergeGuildBaseInfo(com.dj.protobuf.guild.GuildBaseInfo value) {
      if (guildBaseInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            guildBaseInfo_ != null &&
            guildBaseInfo_ != com.dj.protobuf.guild.GuildBaseInfo.getDefaultInstance()) {
          guildBaseInfo_ =
            com.dj.protobuf.guild.GuildBaseInfo.newBuilder(guildBaseInfo_).mergeFrom(value).buildPartial();
        } else {
          guildBaseInfo_ = value;
        }
        onChanged();
      } else {
        guildBaseInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public Builder clearGuildBaseInfo() {
      if (guildBaseInfoBuilder_ == null) {
        guildBaseInfo_ = null;
        onChanged();
      } else {
        guildBaseInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public com.dj.protobuf.guild.GuildBaseInfo.Builder getGuildBaseInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getGuildBaseInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    public com.dj.protobuf.guild.GuildBaseInfoOrBuilder getGuildBaseInfoOrBuilder() {
      if (guildBaseInfoBuilder_ != null) {
        return guildBaseInfoBuilder_.getMessageOrBuilder();
      } else {
        return guildBaseInfo_ == null ?
            com.dj.protobuf.guild.GuildBaseInfo.getDefaultInstance() : guildBaseInfo_;
      }
    }
    /**
     * <pre>
     *&#47; &lt;summary&gt;
     * / 更新后的基本信息
     * / &lt;/summary&gt;
     * </pre>
     *
     * <code>optional .Protocols.GuildBaseInfo guildBaseInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.guild.GuildBaseInfo, com.dj.protobuf.guild.GuildBaseInfo.Builder, com.dj.protobuf.guild.GuildBaseInfoOrBuilder> 
        getGuildBaseInfoFieldBuilder() {
      if (guildBaseInfoBuilder_ == null) {
        guildBaseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.guild.GuildBaseInfo, com.dj.protobuf.guild.GuildBaseInfo.Builder, com.dj.protobuf.guild.GuildBaseInfoOrBuilder>(
                getGuildBaseInfo(),
                getParentForChildren(),
                isClean());
        guildBaseInfo_ = null;
      }
      return guildBaseInfoBuilder_;
    }

    private com.dj.protobuf.guild.GuildKickReq req_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.guild.GuildKickReq, com.dj.protobuf.guild.GuildKickReq.Builder, com.dj.protobuf.guild.GuildKickReqOrBuilder> reqBuilder_;
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public boolean hasReq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public com.dj.protobuf.guild.GuildKickReq getReq() {
      if (reqBuilder_ == null) {
        return req_ == null ? com.dj.protobuf.guild.GuildKickReq.getDefaultInstance() : req_;
      } else {
        return reqBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public Builder setReq(com.dj.protobuf.guild.GuildKickReq value) {
      if (reqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        req_ = value;
        onChanged();
      } else {
        reqBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public Builder setReq(
        com.dj.protobuf.guild.GuildKickReq.Builder builderForValue) {
      if (reqBuilder_ == null) {
        req_ = builderForValue.build();
        onChanged();
      } else {
        reqBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public Builder mergeReq(com.dj.protobuf.guild.GuildKickReq value) {
      if (reqBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            req_ != null &&
            req_ != com.dj.protobuf.guild.GuildKickReq.getDefaultInstance()) {
          req_ =
            com.dj.protobuf.guild.GuildKickReq.newBuilder(req_).mergeFrom(value).buildPartial();
        } else {
          req_ = value;
        }
        onChanged();
      } else {
        reqBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public Builder clearReq() {
      if (reqBuilder_ == null) {
        req_ = null;
        onChanged();
      } else {
        reqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public com.dj.protobuf.guild.GuildKickReq.Builder getReqBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getReqFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    public com.dj.protobuf.guild.GuildKickReqOrBuilder getReqOrBuilder() {
      if (reqBuilder_ != null) {
        return reqBuilder_.getMessageOrBuilder();
      } else {
        return req_ == null ?
            com.dj.protobuf.guild.GuildKickReq.getDefaultInstance() : req_;
      }
    }
    /**
     * <code>optional .Protocols.GuildKickReq req = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.guild.GuildKickReq, com.dj.protobuf.guild.GuildKickReq.Builder, com.dj.protobuf.guild.GuildKickReqOrBuilder> 
        getReqFieldBuilder() {
      if (reqBuilder_ == null) {
        reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.guild.GuildKickReq, com.dj.protobuf.guild.GuildKickReq.Builder, com.dj.protobuf.guild.GuildKickReqOrBuilder>(
                getReq(),
                getParentForChildren(),
                isClean());
        req_ = null;
      }
      return reqBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.GuildKickRsp)
  }

  // @@protoc_insertion_point(class_scope:Protocols.GuildKickRsp)
  private static final com.dj.protobuf.guild.GuildKickRsp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.guild.GuildKickRsp();
  }

  public static com.dj.protobuf.guild.GuildKickRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GuildKickRsp>
      PARSER = new com.google.protobuf.AbstractParser<GuildKickRsp>() {
    public GuildKickRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GuildKickRsp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GuildKickRsp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GuildKickRsp> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.guild.GuildKickRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

