// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guild.proto

package com.dj.protobuf.guild;

public interface GuildMemberListRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.GuildMemberListRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  boolean hasErrorID();
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID();

  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 成员信息和对应的在线信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>repeated .Protocols.GuildMemberInfo members = 2;</code>
   */
  java.util.List<com.dj.protobuf.guild.GuildMemberInfo> 
      getMembersList();
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 成员信息和对应的在线信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>repeated .Protocols.GuildMemberInfo members = 2;</code>
   */
  com.dj.protobuf.guild.GuildMemberInfo getMembers(int index);
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 成员信息和对应的在线信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>repeated .Protocols.GuildMemberInfo members = 2;</code>
   */
  int getMembersCount();
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 成员信息和对应的在线信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>repeated .Protocols.GuildMemberInfo members = 2;</code>
   */
  java.util.List<? extends com.dj.protobuf.guild.GuildMemberInfoOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 成员信息和对应的在线信息
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>repeated .Protocols.GuildMemberInfo members = 2;</code>
   */
  com.dj.protobuf.guild.GuildMemberInfoOrBuilder getMembersOrBuilder(
      int index);
}
