// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GuildBattle.proto

package com.dj.protobuf.guildBattle;

public interface BattleBuildListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.BattleBuildListReq)
    com.google.protobuf.MessageOrBuilder {
}
