// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GuildBattle.proto

package com.dj.protobuf.guildBattle;

public interface BattleBuildUpdateNtfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.BattleBuildUpdateNtf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .Protocols.GuildBattleBuildInfo build = 1;</code>
   */
  boolean hasBuild();
  /**
   * <code>optional .Protocols.GuildBattleBuildInfo build = 1;</code>
   */
  com.dj.protobuf.guildBattle.GuildBattleBuildInfo getBuild();
  /**
   * <code>optional .Protocols.GuildBattleBuildInfo build = 1;</code>
   */
  com.dj.protobuf.guildBattle.GuildBattleBuildInfoOrBuilder getBuildOrBuilder();
}
