// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GuildBattle.proto

package com.dj.protobuf.guildBattle;

/**
 * Protobuf type {@code Protocols.GuildBattleBuildInfo}
 */
public  final class GuildBattleBuildInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.GuildBattleBuildInfo)
    GuildBattleBuildInfoOrBuilder {
  // Use GuildBattleBuildInfo.newBuilder() to construct.
  private GuildBattleBuildInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GuildBattleBuildInfo() {
    buildID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GuildBattleBuildInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            buildID_ = input.readInt32();
            break;
          }
          case 18: {
            com.dj.protobuf.common.BaseRoleInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = holdRoleInfo_.toBuilder();
            }
            holdRoleInfo_ = input.readMessage(com.dj.protobuf.common.BaseRoleInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(holdRoleInfo_);
              holdRoleInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_GuildBattleBuildInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_GuildBattleBuildInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.guildBattle.GuildBattleBuildInfo.class, com.dj.protobuf.guildBattle.GuildBattleBuildInfo.Builder.class);
  }

  private int bitField0_;
  public static final int BUILDID_FIELD_NUMBER = 1;
  private int buildID_;
  /**
   * <pre>
   * 建筑id
   * </pre>
   *
   * <code>optional int32 buildID = 1;</code>
   */
  public boolean hasBuildID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * 建筑id
   * </pre>
   *
   * <code>optional int32 buildID = 1;</code>
   */
  public int getBuildID() {
    return buildID_;
  }

  public static final int HOLDROLEINFO_FIELD_NUMBER = 2;
  private com.dj.protobuf.common.BaseRoleInfo holdRoleInfo_;
  /**
   * <pre>
   * 占领玩家
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
   */
  public boolean hasHoldRoleInfo() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * 占领玩家
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
   */
  public com.dj.protobuf.common.BaseRoleInfo getHoldRoleInfo() {
    return holdRoleInfo_ == null ? com.dj.protobuf.common.BaseRoleInfo.getDefaultInstance() : holdRoleInfo_;
  }
  /**
   * <pre>
   * 占领玩家
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
   */
  public com.dj.protobuf.common.BaseRoleInfoOrBuilder getHoldRoleInfoOrBuilder() {
    return holdRoleInfo_ == null ? com.dj.protobuf.common.BaseRoleInfo.getDefaultInstance() : holdRoleInfo_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, buildID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getHoldRoleInfo());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, buildID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHoldRoleInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.guildBattle.GuildBattleBuildInfo)) {
      return super.equals(obj);
    }
    com.dj.protobuf.guildBattle.GuildBattleBuildInfo other = (com.dj.protobuf.guildBattle.GuildBattleBuildInfo) obj;

    boolean result = true;
    result = result && (hasBuildID() == other.hasBuildID());
    if (hasBuildID()) {
      result = result && (getBuildID()
          == other.getBuildID());
    }
    result = result && (hasHoldRoleInfo() == other.hasHoldRoleInfo());
    if (hasHoldRoleInfo()) {
      result = result && getHoldRoleInfo()
          .equals(other.getHoldRoleInfo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasBuildID()) {
      hash = (37 * hash) + BUILDID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildID();
    }
    if (hasHoldRoleInfo()) {
      hash = (37 * hash) + HOLDROLEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getHoldRoleInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.guildBattle.GuildBattleBuildInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protocols.GuildBattleBuildInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.GuildBattleBuildInfo)
      com.dj.protobuf.guildBattle.GuildBattleBuildInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_GuildBattleBuildInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_GuildBattleBuildInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.guildBattle.GuildBattleBuildInfo.class, com.dj.protobuf.guildBattle.GuildBattleBuildInfo.Builder.class);
    }

    // Construct using com.dj.protobuf.guildBattle.GuildBattleBuildInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHoldRoleInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      buildID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (holdRoleInfoBuilder_ == null) {
        holdRoleInfo_ = null;
      } else {
        holdRoleInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_GuildBattleBuildInfo_descriptor;
    }

    public com.dj.protobuf.guildBattle.GuildBattleBuildInfo getDefaultInstanceForType() {
      return com.dj.protobuf.guildBattle.GuildBattleBuildInfo.getDefaultInstance();
    }

    public com.dj.protobuf.guildBattle.GuildBattleBuildInfo build() {
      com.dj.protobuf.guildBattle.GuildBattleBuildInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.guildBattle.GuildBattleBuildInfo buildPartial() {
      com.dj.protobuf.guildBattle.GuildBattleBuildInfo result = new com.dj.protobuf.guildBattle.GuildBattleBuildInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.buildID_ = buildID_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (holdRoleInfoBuilder_ == null) {
        result.holdRoleInfo_ = holdRoleInfo_;
      } else {
        result.holdRoleInfo_ = holdRoleInfoBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.guildBattle.GuildBattleBuildInfo) {
        return mergeFrom((com.dj.protobuf.guildBattle.GuildBattleBuildInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.guildBattle.GuildBattleBuildInfo other) {
      if (other == com.dj.protobuf.guildBattle.GuildBattleBuildInfo.getDefaultInstance()) return this;
      if (other.hasBuildID()) {
        setBuildID(other.getBuildID());
      }
      if (other.hasHoldRoleInfo()) {
        mergeHoldRoleInfo(other.getHoldRoleInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.guildBattle.GuildBattleBuildInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.guildBattle.GuildBattleBuildInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int buildID_ ;
    /**
     * <pre>
     * 建筑id
     * </pre>
     *
     * <code>optional int32 buildID = 1;</code>
     */
    public boolean hasBuildID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 建筑id
     * </pre>
     *
     * <code>optional int32 buildID = 1;</code>
     */
    public int getBuildID() {
      return buildID_;
    }
    /**
     * <pre>
     * 建筑id
     * </pre>
     *
     * <code>optional int32 buildID = 1;</code>
     */
    public Builder setBuildID(int value) {
      bitField0_ |= 0x00000001;
      buildID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 建筑id
     * </pre>
     *
     * <code>optional int32 buildID = 1;</code>
     */
    public Builder clearBuildID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      buildID_ = 0;
      onChanged();
      return this;
    }

    private com.dj.protobuf.common.BaseRoleInfo holdRoleInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.common.BaseRoleInfo, com.dj.protobuf.common.BaseRoleInfo.Builder, com.dj.protobuf.common.BaseRoleInfoOrBuilder> holdRoleInfoBuilder_;
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public boolean hasHoldRoleInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public com.dj.protobuf.common.BaseRoleInfo getHoldRoleInfo() {
      if (holdRoleInfoBuilder_ == null) {
        return holdRoleInfo_ == null ? com.dj.protobuf.common.BaseRoleInfo.getDefaultInstance() : holdRoleInfo_;
      } else {
        return holdRoleInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public Builder setHoldRoleInfo(com.dj.protobuf.common.BaseRoleInfo value) {
      if (holdRoleInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        holdRoleInfo_ = value;
        onChanged();
      } else {
        holdRoleInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public Builder setHoldRoleInfo(
        com.dj.protobuf.common.BaseRoleInfo.Builder builderForValue) {
      if (holdRoleInfoBuilder_ == null) {
        holdRoleInfo_ = builderForValue.build();
        onChanged();
      } else {
        holdRoleInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public Builder mergeHoldRoleInfo(com.dj.protobuf.common.BaseRoleInfo value) {
      if (holdRoleInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            holdRoleInfo_ != null &&
            holdRoleInfo_ != com.dj.protobuf.common.BaseRoleInfo.getDefaultInstance()) {
          holdRoleInfo_ =
            com.dj.protobuf.common.BaseRoleInfo.newBuilder(holdRoleInfo_).mergeFrom(value).buildPartial();
        } else {
          holdRoleInfo_ = value;
        }
        onChanged();
      } else {
        holdRoleInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public Builder clearHoldRoleInfo() {
      if (holdRoleInfoBuilder_ == null) {
        holdRoleInfo_ = null;
        onChanged();
      } else {
        holdRoleInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public com.dj.protobuf.common.BaseRoleInfo.Builder getHoldRoleInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getHoldRoleInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    public com.dj.protobuf.common.BaseRoleInfoOrBuilder getHoldRoleInfoOrBuilder() {
      if (holdRoleInfoBuilder_ != null) {
        return holdRoleInfoBuilder_.getMessageOrBuilder();
      } else {
        return holdRoleInfo_ == null ?
            com.dj.protobuf.common.BaseRoleInfo.getDefaultInstance() : holdRoleInfo_;
      }
    }
    /**
     * <pre>
     * 占领玩家
     * </pre>
     *
     * <code>optional .Protocols.BaseRoleInfo holdRoleInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.common.BaseRoleInfo, com.dj.protobuf.common.BaseRoleInfo.Builder, com.dj.protobuf.common.BaseRoleInfoOrBuilder> 
        getHoldRoleInfoFieldBuilder() {
      if (holdRoleInfoBuilder_ == null) {
        holdRoleInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.common.BaseRoleInfo, com.dj.protobuf.common.BaseRoleInfo.Builder, com.dj.protobuf.common.BaseRoleInfoOrBuilder>(
                getHoldRoleInfo(),
                getParentForChildren(),
                isClean());
        holdRoleInfo_ = null;
      }
      return holdRoleInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.GuildBattleBuildInfo)
  }

  // @@protoc_insertion_point(class_scope:Protocols.GuildBattleBuildInfo)
  private static final com.dj.protobuf.guildBattle.GuildBattleBuildInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.guildBattle.GuildBattleBuildInfo();
  }

  public static com.dj.protobuf.guildBattle.GuildBattleBuildInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GuildBattleBuildInfo>
      PARSER = new com.google.protobuf.AbstractParser<GuildBattleBuildInfo>() {
    public GuildBattleBuildInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GuildBattleBuildInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GuildBattleBuildInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GuildBattleBuildInfo> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.guildBattle.GuildBattleBuildInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

