// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GuildBattle.proto

package com.dj.protobuf.guildBattle;

/**
 * Protobuf type {@code Protocols.StartBattleMeetEggNtf}
 */
public  final class StartBattleMeetEggNtf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.StartBattleMeetEggNtf)
    StartBattleMeetEggNtfOrBuilder {
  // Use StartBattleMeetEggNtf.newBuilder() to construct.
  private StartBattleMeetEggNtf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartBattleMeetEggNtf() {
    errorID_ = 0;
    dropItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StartBattleMeetEggNtf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.dj.protobuf.ErrorIDOuterClass.ErrorID value = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              errorID_ = rawValue;
            }
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              dropItems_ = new java.util.ArrayList<com.dj.protobuf.guildBattle.BattleMeetEggDropItem>();
              mutable_bitField0_ |= 0x00000002;
            }
            dropItems_.add(
                input.readMessage(com.dj.protobuf.guildBattle.BattleMeetEggDropItem.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        dropItems_ = java.util.Collections.unmodifiableList(dropItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_StartBattleMeetEggNtf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_StartBattleMeetEggNtf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.class, com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.Builder.class);
  }

  private int bitField0_;
  public static final int ERRORID_FIELD_NUMBER = 1;
  private int errorID_;
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public boolean hasErrorID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
    com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
    return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
  }

  public static final int DROPITEMS_FIELD_NUMBER = 2;
  private java.util.List<com.dj.protobuf.guildBattle.BattleMeetEggDropItem> dropItems_;
  /**
   * <pre>
   *初始掉落id
   * </pre>
   *
   * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
   */
  public java.util.List<com.dj.protobuf.guildBattle.BattleMeetEggDropItem> getDropItemsList() {
    return dropItems_;
  }
  /**
   * <pre>
   *初始掉落id
   * </pre>
   *
   * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
   */
  public java.util.List<? extends com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder> 
      getDropItemsOrBuilderList() {
    return dropItems_;
  }
  /**
   * <pre>
   *初始掉落id
   * </pre>
   *
   * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
   */
  public int getDropItemsCount() {
    return dropItems_.size();
  }
  /**
   * <pre>
   *初始掉落id
   * </pre>
   *
   * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
   */
  public com.dj.protobuf.guildBattle.BattleMeetEggDropItem getDropItems(int index) {
    return dropItems_.get(index);
  }
  /**
   * <pre>
   *初始掉落id
   * </pre>
   *
   * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
   */
  public com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder getDropItemsOrBuilder(
      int index) {
    return dropItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, errorID_);
    }
    for (int i = 0; i < dropItems_.size(); i++) {
      output.writeMessage(2, dropItems_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errorID_);
    }
    for (int i = 0; i < dropItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, dropItems_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.guildBattle.StartBattleMeetEggNtf)) {
      return super.equals(obj);
    }
    com.dj.protobuf.guildBattle.StartBattleMeetEggNtf other = (com.dj.protobuf.guildBattle.StartBattleMeetEggNtf) obj;

    boolean result = true;
    result = result && (hasErrorID() == other.hasErrorID());
    if (hasErrorID()) {
      result = result && errorID_ == other.errorID_;
    }
    result = result && getDropItemsList()
        .equals(other.getDropItemsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasErrorID()) {
      hash = (37 * hash) + ERRORID_FIELD_NUMBER;
      hash = (53 * hash) + errorID_;
    }
    if (getDropItemsCount() > 0) {
      hash = (37 * hash) + DROPITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getDropItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.guildBattle.StartBattleMeetEggNtf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protocols.StartBattleMeetEggNtf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.StartBattleMeetEggNtf)
      com.dj.protobuf.guildBattle.StartBattleMeetEggNtfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_StartBattleMeetEggNtf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_StartBattleMeetEggNtf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.class, com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.Builder.class);
    }

    // Construct using com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDropItemsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      errorID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (dropItemsBuilder_ == null) {
        dropItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        dropItemsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.guildBattle.GuildBattle.internal_static_Protocols_StartBattleMeetEggNtf_descriptor;
    }

    public com.dj.protobuf.guildBattle.StartBattleMeetEggNtf getDefaultInstanceForType() {
      return com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.getDefaultInstance();
    }

    public com.dj.protobuf.guildBattle.StartBattleMeetEggNtf build() {
      com.dj.protobuf.guildBattle.StartBattleMeetEggNtf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.guildBattle.StartBattleMeetEggNtf buildPartial() {
      com.dj.protobuf.guildBattle.StartBattleMeetEggNtf result = new com.dj.protobuf.guildBattle.StartBattleMeetEggNtf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.errorID_ = errorID_;
      if (dropItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          dropItems_ = java.util.Collections.unmodifiableList(dropItems_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.dropItems_ = dropItems_;
      } else {
        result.dropItems_ = dropItemsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.guildBattle.StartBattleMeetEggNtf) {
        return mergeFrom((com.dj.protobuf.guildBattle.StartBattleMeetEggNtf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.guildBattle.StartBattleMeetEggNtf other) {
      if (other == com.dj.protobuf.guildBattle.StartBattleMeetEggNtf.getDefaultInstance()) return this;
      if (other.hasErrorID()) {
        setErrorID(other.getErrorID());
      }
      if (dropItemsBuilder_ == null) {
        if (!other.dropItems_.isEmpty()) {
          if (dropItems_.isEmpty()) {
            dropItems_ = other.dropItems_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDropItemsIsMutable();
            dropItems_.addAll(other.dropItems_);
          }
          onChanged();
        }
      } else {
        if (!other.dropItems_.isEmpty()) {
          if (dropItemsBuilder_.isEmpty()) {
            dropItemsBuilder_.dispose();
            dropItemsBuilder_ = null;
            dropItems_ = other.dropItems_;
            bitField0_ = (bitField0_ & ~0x00000002);
            dropItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDropItemsFieldBuilder() : null;
          } else {
            dropItemsBuilder_.addAllMessages(other.dropItems_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.guildBattle.StartBattleMeetEggNtf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.guildBattle.StartBattleMeetEggNtf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorID_ = 0;
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public boolean hasErrorID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
      com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
      return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder setErrorID(com.dj.protobuf.ErrorIDOuterClass.ErrorID value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      errorID_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder clearErrorID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorID_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.dj.protobuf.guildBattle.BattleMeetEggDropItem> dropItems_ =
      java.util.Collections.emptyList();
    private void ensureDropItemsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        dropItems_ = new java.util.ArrayList<com.dj.protobuf.guildBattle.BattleMeetEggDropItem>(dropItems_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dj.protobuf.guildBattle.BattleMeetEggDropItem, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder, com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder> dropItemsBuilder_;

    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public java.util.List<com.dj.protobuf.guildBattle.BattleMeetEggDropItem> getDropItemsList() {
      if (dropItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dropItems_);
      } else {
        return dropItemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public int getDropItemsCount() {
      if (dropItemsBuilder_ == null) {
        return dropItems_.size();
      } else {
        return dropItemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public com.dj.protobuf.guildBattle.BattleMeetEggDropItem getDropItems(int index) {
      if (dropItemsBuilder_ == null) {
        return dropItems_.get(index);
      } else {
        return dropItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder setDropItems(
        int index, com.dj.protobuf.guildBattle.BattleMeetEggDropItem value) {
      if (dropItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDropItemsIsMutable();
        dropItems_.set(index, value);
        onChanged();
      } else {
        dropItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder setDropItems(
        int index, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder builderForValue) {
      if (dropItemsBuilder_ == null) {
        ensureDropItemsIsMutable();
        dropItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        dropItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder addDropItems(com.dj.protobuf.guildBattle.BattleMeetEggDropItem value) {
      if (dropItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDropItemsIsMutable();
        dropItems_.add(value);
        onChanged();
      } else {
        dropItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder addDropItems(
        int index, com.dj.protobuf.guildBattle.BattleMeetEggDropItem value) {
      if (dropItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDropItemsIsMutable();
        dropItems_.add(index, value);
        onChanged();
      } else {
        dropItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder addDropItems(
        com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder builderForValue) {
      if (dropItemsBuilder_ == null) {
        ensureDropItemsIsMutable();
        dropItems_.add(builderForValue.build());
        onChanged();
      } else {
        dropItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder addDropItems(
        int index, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder builderForValue) {
      if (dropItemsBuilder_ == null) {
        ensureDropItemsIsMutable();
        dropItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        dropItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder addAllDropItems(
        java.lang.Iterable<? extends com.dj.protobuf.guildBattle.BattleMeetEggDropItem> values) {
      if (dropItemsBuilder_ == null) {
        ensureDropItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dropItems_);
        onChanged();
      } else {
        dropItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder clearDropItems() {
      if (dropItemsBuilder_ == null) {
        dropItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        dropItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public Builder removeDropItems(int index) {
      if (dropItemsBuilder_ == null) {
        ensureDropItemsIsMutable();
        dropItems_.remove(index);
        onChanged();
      } else {
        dropItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder getDropItemsBuilder(
        int index) {
      return getDropItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder getDropItemsOrBuilder(
        int index) {
      if (dropItemsBuilder_ == null) {
        return dropItems_.get(index);  } else {
        return dropItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public java.util.List<? extends com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder> 
         getDropItemsOrBuilderList() {
      if (dropItemsBuilder_ != null) {
        return dropItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dropItems_);
      }
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder addDropItemsBuilder() {
      return getDropItemsFieldBuilder().addBuilder(
          com.dj.protobuf.guildBattle.BattleMeetEggDropItem.getDefaultInstance());
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder addDropItemsBuilder(
        int index) {
      return getDropItemsFieldBuilder().addBuilder(
          index, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.getDefaultInstance());
    }
    /**
     * <pre>
     *初始掉落id
     * </pre>
     *
     * <code>repeated .Protocols.BattleMeetEggDropItem dropItems = 2;</code>
     */
    public java.util.List<com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder> 
         getDropItemsBuilderList() {
      return getDropItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dj.protobuf.guildBattle.BattleMeetEggDropItem, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder, com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder> 
        getDropItemsFieldBuilder() {
      if (dropItemsBuilder_ == null) {
        dropItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dj.protobuf.guildBattle.BattleMeetEggDropItem, com.dj.protobuf.guildBattle.BattleMeetEggDropItem.Builder, com.dj.protobuf.guildBattle.BattleMeetEggDropItemOrBuilder>(
                dropItems_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        dropItems_ = null;
      }
      return dropItemsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.StartBattleMeetEggNtf)
  }

  // @@protoc_insertion_point(class_scope:Protocols.StartBattleMeetEggNtf)
  private static final com.dj.protobuf.guildBattle.StartBattleMeetEggNtf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.guildBattle.StartBattleMeetEggNtf();
  }

  public static com.dj.protobuf.guildBattle.StartBattleMeetEggNtf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<StartBattleMeetEggNtf>
      PARSER = new com.google.protobuf.AbstractParser<StartBattleMeetEggNtf>() {
    public StartBattleMeetEggNtf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new StartBattleMeetEggNtf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StartBattleMeetEggNtf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartBattleMeetEggNtf> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.guildBattle.StartBattleMeetEggNtf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

