// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OutSideMap.proto

package com.dj.protobuf.outSideMap;

public interface BuildInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.BuildInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *建筑id
   * </pre>
   *
   * <code>optional int32 buildID = 1;</code>
   */
  boolean hasBuildID();
  /**
   * <pre>
   *建筑id
   * </pre>
   *
   * <code>optional int32 buildID = 1;</code>
   */
  int getBuildID();

  /**
   * <pre>
   *占领角色id
   * </pre>
   *
   * <code>optional int32 holdRoleID = 2;</code>
   */
  boolean hasHoldRoleID();
  /**
   * <pre>
   *占领角色id
   * </pre>
   *
   * <code>optional int32 holdRoleID = 2;</code>
   */
  int getHoldRoleID();
}
