// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quest.proto

package com.dj.protobuf.quest;

public interface QuestListRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.QuestListRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .Protocols.QuestInfo&gt; quests = 1;</code>
   */
  int getQuestsCount();
  /**
   * <code>map&lt;int32, .Protocols.QuestInfo&gt; quests = 1;</code>
   */
  boolean containsQuests(
      int key);
  /**
   * Use {@link #getQuestsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.dj.protobuf.quest.QuestInfo>
  getQuests();
  /**
   * <code>map&lt;int32, .Protocols.QuestInfo&gt; quests = 1;</code>
   */
  java.util.Map<java.lang.Integer, com.dj.protobuf.quest.QuestInfo>
  getQuestsMap();
  /**
   * <code>map&lt;int32, .Protocols.QuestInfo&gt; quests = 1;</code>
   */

  com.dj.protobuf.quest.QuestInfo getQuestsOrDefault(
      int key,
      com.dj.protobuf.quest.QuestInfo defaultValue);
  /**
   * <code>map&lt;int32, .Protocols.QuestInfo&gt; quests = 1;</code>
   */

  com.dj.protobuf.quest.QuestInfo getQuestsOrThrow(
      int key);

  /**
   * <code>optional .ErrorID error = 2;</code>
   */
  boolean hasError();
  /**
   * <code>optional .ErrorID error = 2;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getError();
}
