// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Summon.proto

package com.dj.protobuf.summon;

public interface SummonInvestReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.SummonInvestReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 邮件索引
   * </pre>
   *
   * <code>optional int32 index = 1;</code>
   */
  boolean hasIndex();
  /**
   * <pre>
   * 邮件索引
   * </pre>
   *
   * <code>optional int32 index = 1;</code>
   */
  int getIndex();

  /**
   * <pre>
   * 是否放弃
   * </pre>
   *
   * <code>optional bool gaveUp = 2;</code>
   */
  boolean hasGaveUp();
  /**
   * <pre>
   * 是否放弃
   * </pre>
   *
   * <code>optional bool gaveUp = 2;</code>
   */
  boolean getGaveUp();
}
