// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Summon.proto

package com.dj.protobuf.summon;

/**
 * Protobuf type {@code Protocols.SummonMailRefreshRsp}
 */
public  final class SummonMailRefreshRsp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.SummonMailRefreshRsp)
    SummonMailRefreshRspOrBuilder {
  // Use SummonMailRefreshRsp.newBuilder() to construct.
  private SummonMailRefreshRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SummonMailRefreshRsp() {
    errorID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SummonMailRefreshRsp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            com.dj.protobuf.ErrorIDOuterClass.ErrorID value = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              errorID_ = rawValue;
            }
            break;
          }
          case 18: {
            com.dj.protobuf.summon.SummonMailRefreshReq.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = req_.toBuilder();
            }
            req_ = input.readMessage(com.dj.protobuf.summon.SummonMailRefreshReq.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(req_);
              req_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            com.dj.protobuf.summon.SummonMailInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = mail_.toBuilder();
            }
            mail_ = input.readMessage(com.dj.protobuf.summon.SummonMailInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(mail_);
              mail_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.summon.Summon.internal_static_Protocols_SummonMailRefreshRsp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.summon.Summon.internal_static_Protocols_SummonMailRefreshRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.summon.SummonMailRefreshRsp.class, com.dj.protobuf.summon.SummonMailRefreshRsp.Builder.class);
  }

  private int bitField0_;
  public static final int ERRORID_FIELD_NUMBER = 1;
  private int errorID_;
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public boolean hasErrorID() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
    com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
    return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
  }

  public static final int REQ_FIELD_NUMBER = 2;
  private com.dj.protobuf.summon.SummonMailRefreshReq req_;
  /**
   * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
   */
  public boolean hasReq() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
   */
  public com.dj.protobuf.summon.SummonMailRefreshReq getReq() {
    return req_ == null ? com.dj.protobuf.summon.SummonMailRefreshReq.getDefaultInstance() : req_;
  }
  /**
   * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
   */
  public com.dj.protobuf.summon.SummonMailRefreshReqOrBuilder getReqOrBuilder() {
    return req_ == null ? com.dj.protobuf.summon.SummonMailRefreshReq.getDefaultInstance() : req_;
  }

  public static final int MAIL_FIELD_NUMBER = 3;
  private com.dj.protobuf.summon.SummonMailInfo mail_;
  /**
   * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
   */
  public boolean hasMail() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
   */
  public com.dj.protobuf.summon.SummonMailInfo getMail() {
    return mail_ == null ? com.dj.protobuf.summon.SummonMailInfo.getDefaultInstance() : mail_;
  }
  /**
   * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
   */
  public com.dj.protobuf.summon.SummonMailInfoOrBuilder getMailOrBuilder() {
    return mail_ == null ? com.dj.protobuf.summon.SummonMailInfo.getDefaultInstance() : mail_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeEnum(1, errorID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getReq());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getMail());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, errorID_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getReq());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMail());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.summon.SummonMailRefreshRsp)) {
      return super.equals(obj);
    }
    com.dj.protobuf.summon.SummonMailRefreshRsp other = (com.dj.protobuf.summon.SummonMailRefreshRsp) obj;

    boolean result = true;
    result = result && (hasErrorID() == other.hasErrorID());
    if (hasErrorID()) {
      result = result && errorID_ == other.errorID_;
    }
    result = result && (hasReq() == other.hasReq());
    if (hasReq()) {
      result = result && getReq()
          .equals(other.getReq());
    }
    result = result && (hasMail() == other.hasMail());
    if (hasMail()) {
      result = result && getMail()
          .equals(other.getMail());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasErrorID()) {
      hash = (37 * hash) + ERRORID_FIELD_NUMBER;
      hash = (53 * hash) + errorID_;
    }
    if (hasReq()) {
      hash = (37 * hash) + REQ_FIELD_NUMBER;
      hash = (53 * hash) + getReq().hashCode();
    }
    if (hasMail()) {
      hash = (37 * hash) + MAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMail().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.summon.SummonMailRefreshRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.summon.SummonMailRefreshRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protocols.SummonMailRefreshRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.SummonMailRefreshRsp)
      com.dj.protobuf.summon.SummonMailRefreshRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.summon.Summon.internal_static_Protocols_SummonMailRefreshRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.summon.Summon.internal_static_Protocols_SummonMailRefreshRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.summon.SummonMailRefreshRsp.class, com.dj.protobuf.summon.SummonMailRefreshRsp.Builder.class);
    }

    // Construct using com.dj.protobuf.summon.SummonMailRefreshRsp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getReqFieldBuilder();
        getMailFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      errorID_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (reqBuilder_ == null) {
        req_ = null;
      } else {
        reqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (mailBuilder_ == null) {
        mail_ = null;
      } else {
        mailBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.summon.Summon.internal_static_Protocols_SummonMailRefreshRsp_descriptor;
    }

    public com.dj.protobuf.summon.SummonMailRefreshRsp getDefaultInstanceForType() {
      return com.dj.protobuf.summon.SummonMailRefreshRsp.getDefaultInstance();
    }

    public com.dj.protobuf.summon.SummonMailRefreshRsp build() {
      com.dj.protobuf.summon.SummonMailRefreshRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.summon.SummonMailRefreshRsp buildPartial() {
      com.dj.protobuf.summon.SummonMailRefreshRsp result = new com.dj.protobuf.summon.SummonMailRefreshRsp(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.errorID_ = errorID_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (reqBuilder_ == null) {
        result.req_ = req_;
      } else {
        result.req_ = reqBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (mailBuilder_ == null) {
        result.mail_ = mail_;
      } else {
        result.mail_ = mailBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.summon.SummonMailRefreshRsp) {
        return mergeFrom((com.dj.protobuf.summon.SummonMailRefreshRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.summon.SummonMailRefreshRsp other) {
      if (other == com.dj.protobuf.summon.SummonMailRefreshRsp.getDefaultInstance()) return this;
      if (other.hasErrorID()) {
        setErrorID(other.getErrorID());
      }
      if (other.hasReq()) {
        mergeReq(other.getReq());
      }
      if (other.hasMail()) {
        mergeMail(other.getMail());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.summon.SummonMailRefreshRsp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.summon.SummonMailRefreshRsp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int errorID_ = 0;
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public boolean hasErrorID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID() {
      com.dj.protobuf.ErrorIDOuterClass.ErrorID result = com.dj.protobuf.ErrorIDOuterClass.ErrorID.valueOf(errorID_);
      return result == null ? com.dj.protobuf.ErrorIDOuterClass.ErrorID.OK : result;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder setErrorID(com.dj.protobuf.ErrorIDOuterClass.ErrorID value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      errorID_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .ErrorID errorID = 1;</code>
     */
    public Builder clearErrorID() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorID_ = 0;
      onChanged();
      return this;
    }

    private com.dj.protobuf.summon.SummonMailRefreshReq req_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.summon.SummonMailRefreshReq, com.dj.protobuf.summon.SummonMailRefreshReq.Builder, com.dj.protobuf.summon.SummonMailRefreshReqOrBuilder> reqBuilder_;
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public boolean hasReq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public com.dj.protobuf.summon.SummonMailRefreshReq getReq() {
      if (reqBuilder_ == null) {
        return req_ == null ? com.dj.protobuf.summon.SummonMailRefreshReq.getDefaultInstance() : req_;
      } else {
        return reqBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public Builder setReq(com.dj.protobuf.summon.SummonMailRefreshReq value) {
      if (reqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        req_ = value;
        onChanged();
      } else {
        reqBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public Builder setReq(
        com.dj.protobuf.summon.SummonMailRefreshReq.Builder builderForValue) {
      if (reqBuilder_ == null) {
        req_ = builderForValue.build();
        onChanged();
      } else {
        reqBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public Builder mergeReq(com.dj.protobuf.summon.SummonMailRefreshReq value) {
      if (reqBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            req_ != null &&
            req_ != com.dj.protobuf.summon.SummonMailRefreshReq.getDefaultInstance()) {
          req_ =
            com.dj.protobuf.summon.SummonMailRefreshReq.newBuilder(req_).mergeFrom(value).buildPartial();
        } else {
          req_ = value;
        }
        onChanged();
      } else {
        reqBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public Builder clearReq() {
      if (reqBuilder_ == null) {
        req_ = null;
        onChanged();
      } else {
        reqBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public com.dj.protobuf.summon.SummonMailRefreshReq.Builder getReqBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getReqFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    public com.dj.protobuf.summon.SummonMailRefreshReqOrBuilder getReqOrBuilder() {
      if (reqBuilder_ != null) {
        return reqBuilder_.getMessageOrBuilder();
      } else {
        return req_ == null ?
            com.dj.protobuf.summon.SummonMailRefreshReq.getDefaultInstance() : req_;
      }
    }
    /**
     * <code>optional .Protocols.SummonMailRefreshReq req = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.summon.SummonMailRefreshReq, com.dj.protobuf.summon.SummonMailRefreshReq.Builder, com.dj.protobuf.summon.SummonMailRefreshReqOrBuilder> 
        getReqFieldBuilder() {
      if (reqBuilder_ == null) {
        reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.summon.SummonMailRefreshReq, com.dj.protobuf.summon.SummonMailRefreshReq.Builder, com.dj.protobuf.summon.SummonMailRefreshReqOrBuilder>(
                getReq(),
                getParentForChildren(),
                isClean());
        req_ = null;
      }
      return reqBuilder_;
    }

    private com.dj.protobuf.summon.SummonMailInfo mail_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.summon.SummonMailInfo, com.dj.protobuf.summon.SummonMailInfo.Builder, com.dj.protobuf.summon.SummonMailInfoOrBuilder> mailBuilder_;
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public boolean hasMail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public com.dj.protobuf.summon.SummonMailInfo getMail() {
      if (mailBuilder_ == null) {
        return mail_ == null ? com.dj.protobuf.summon.SummonMailInfo.getDefaultInstance() : mail_;
      } else {
        return mailBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public Builder setMail(com.dj.protobuf.summon.SummonMailInfo value) {
      if (mailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mail_ = value;
        onChanged();
      } else {
        mailBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public Builder setMail(
        com.dj.protobuf.summon.SummonMailInfo.Builder builderForValue) {
      if (mailBuilder_ == null) {
        mail_ = builderForValue.build();
        onChanged();
      } else {
        mailBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public Builder mergeMail(com.dj.protobuf.summon.SummonMailInfo value) {
      if (mailBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            mail_ != null &&
            mail_ != com.dj.protobuf.summon.SummonMailInfo.getDefaultInstance()) {
          mail_ =
            com.dj.protobuf.summon.SummonMailInfo.newBuilder(mail_).mergeFrom(value).buildPartial();
        } else {
          mail_ = value;
        }
        onChanged();
      } else {
        mailBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public Builder clearMail() {
      if (mailBuilder_ == null) {
        mail_ = null;
        onChanged();
      } else {
        mailBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public com.dj.protobuf.summon.SummonMailInfo.Builder getMailBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMailFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    public com.dj.protobuf.summon.SummonMailInfoOrBuilder getMailOrBuilder() {
      if (mailBuilder_ != null) {
        return mailBuilder_.getMessageOrBuilder();
      } else {
        return mail_ == null ?
            com.dj.protobuf.summon.SummonMailInfo.getDefaultInstance() : mail_;
      }
    }
    /**
     * <code>optional .Protocols.SummonMailInfo mail = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.summon.SummonMailInfo, com.dj.protobuf.summon.SummonMailInfo.Builder, com.dj.protobuf.summon.SummonMailInfoOrBuilder> 
        getMailFieldBuilder() {
      if (mailBuilder_ == null) {
        mailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.summon.SummonMailInfo, com.dj.protobuf.summon.SummonMailInfo.Builder, com.dj.protobuf.summon.SummonMailInfoOrBuilder>(
                getMail(),
                getParentForChildren(),
                isClean());
        mail_ = null;
      }
      return mailBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.SummonMailRefreshRsp)
  }

  // @@protoc_insertion_point(class_scope:Protocols.SummonMailRefreshRsp)
  private static final com.dj.protobuf.summon.SummonMailRefreshRsp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.summon.SummonMailRefreshRsp();
  }

  public static com.dj.protobuf.summon.SummonMailRefreshRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SummonMailRefreshRsp>
      PARSER = new com.google.protobuf.AbstractParser<SummonMailRefreshRsp>() {
    public SummonMailRefreshRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SummonMailRefreshRsp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SummonMailRefreshRsp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SummonMailRefreshRsp> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.summon.SummonMailRefreshRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

