// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Summon.proto

package com.dj.protobuf.summon;

public interface SummonInvestRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.SummonInvestRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  boolean hasErrorID();
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID();

  /**
   * <code>optional .Protocols.SummonInvestReq req = 2;</code>
   */
  boolean hasReq();
  /**
   * <code>optional .Protocols.SummonInvestReq req = 2;</code>
   */
  com.dj.protobuf.summon.SummonInvestReq getReq();
  /**
   * <code>optional .Protocols.SummonInvestReq req = 2;</code>
   */
  com.dj.protobuf.summon.SummonInvestReqOrBuilder getReqOrBuilder();

  /**
   * <pre>
   * 投资剩余时间;秒数
   * </pre>
   *
   * <code>optional int32 investCountDown = 3;</code>
   */
  boolean hasInvestCountDown();
  /**
   * <pre>
   * 投资剩余时间;秒数
   * </pre>
   *
   * <code>optional int32 investCountDown = 3;</code>
   */
  int getInvestCountDown();

  /**
   * <pre>
   * 旅行剩余时间;秒数
   * </pre>
   *
   * <code>optional int32 countDown = 4;</code>
   */
  boolean hasCountDown();
  /**
   * <pre>
   * 旅行剩余时间;秒数
   * </pre>
   *
   * <code>optional int32 countDown = 4;</code>
   */
  int getCountDown();

  /**
   * <pre>
   * 投资奖励
   * </pre>
   *
   * <code>optional .Protocols.SummonInvestReward investReward = 5;</code>
   */
  boolean hasInvestReward();
  /**
   * <pre>
   * 投资奖励
   * </pre>
   *
   * <code>optional .Protocols.SummonInvestReward investReward = 5;</code>
   */
  com.dj.protobuf.summon.SummonInvestReward getInvestReward();
  /**
   * <pre>
   * 投资奖励
   * </pre>
   *
   * <code>optional .Protocols.SummonInvestReward investReward = 5;</code>
   */
  com.dj.protobuf.summon.SummonInvestRewardOrBuilder getInvestRewardOrBuilder();
}
