// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Summon.proto

package com.dj.protobuf.summon;

public interface SummonInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.SummonInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 roleId = 1;</code>
   */
  boolean hasRoleId();
  /**
   * <code>optional uint64 roleId = 1;</code>
   */
  long getRoleId();
}
