// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Scene.proto

package com.dj.protobuf.scene;

/**
 * Protobuf type {@code Protocols.SceneBriefInfo}
 */
public  final class SceneBriefInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.SceneBriefInfo)
    SceneBriefInfoOrBuilder {
  // Use SceneBriefInfo.newBuilder() to construct.
  private SceneBriefInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SceneBriefInfo() {
    id_ = 0L;
    name_ = "";
    level_ = 0;
    themeId_ = 0;
    curPlayerNum_ = 0;
    maxPlayerNum_ = 0;
    isNeedPassword_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SceneBriefInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readUInt64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            name_ = bs;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            level_ = input.readInt32();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000008;
            themeId_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000010;
            curPlayerNum_ = input.readInt32();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000020;
            maxPlayerNum_ = input.readInt32();
            break;
          }
          case 64: {
            bitField0_ |= 0x00000040;
            isNeedPassword_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.scene.Scene.internal_static_Protocols_SceneBriefInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.scene.Scene.internal_static_Protocols_SceneBriefInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.scene.SceneBriefInfo.class, com.dj.protobuf.scene.SceneBriefInfo.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 3;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEVEL_FIELD_NUMBER = 4;
  private int level_;
  /**
   * <code>optional int32 level = 4;</code>
   */
  public boolean hasLevel() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 level = 4;</code>
   */
  public int getLevel() {
    return level_;
  }

  public static final int THEMEID_FIELD_NUMBER = 5;
  private int themeId_;
  /**
   * <code>optional int32 themeId = 5;</code>
   */
  public boolean hasThemeId() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 themeId = 5;</code>
   */
  public int getThemeId() {
    return themeId_;
  }

  public static final int CURPLAYERNUM_FIELD_NUMBER = 6;
  private int curPlayerNum_;
  /**
   * <code>optional int32 curPlayerNum = 6;</code>
   */
  public boolean hasCurPlayerNum() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int32 curPlayerNum = 6;</code>
   */
  public int getCurPlayerNum() {
    return curPlayerNum_;
  }

  public static final int MAXPLAYERNUM_FIELD_NUMBER = 7;
  private int maxPlayerNum_;
  /**
   * <code>optional int32 maxPlayerNum = 7;</code>
   */
  public boolean hasMaxPlayerNum() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int32 maxPlayerNum = 7;</code>
   */
  public int getMaxPlayerNum() {
    return maxPlayerNum_;
  }

  public static final int ISNEEDPASSWORD_FIELD_NUMBER = 8;
  private boolean isNeedPassword_;
  /**
   * <code>optional bool isNeedPassword = 8;</code>
   */
  public boolean hasIsNeedPassword() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional bool isNeedPassword = 8;</code>
   */
  public boolean getIsNeedPassword() {
    return isNeedPassword_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeUInt64(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(4, level_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(5, themeId_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(6, curPlayerNum_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt32(7, maxPlayerNum_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBool(8, isNeedPassword_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, level_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, themeId_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, curPlayerNum_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, maxPlayerNum_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isNeedPassword_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.scene.SceneBriefInfo)) {
      return super.equals(obj);
    }
    com.dj.protobuf.scene.SceneBriefInfo other = (com.dj.protobuf.scene.SceneBriefInfo) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && (getId()
          == other.getId());
    }
    result = result && (hasName() == other.hasName());
    if (hasName()) {
      result = result && getName()
          .equals(other.getName());
    }
    result = result && (hasLevel() == other.hasLevel());
    if (hasLevel()) {
      result = result && (getLevel()
          == other.getLevel());
    }
    result = result && (hasThemeId() == other.hasThemeId());
    if (hasThemeId()) {
      result = result && (getThemeId()
          == other.getThemeId());
    }
    result = result && (hasCurPlayerNum() == other.hasCurPlayerNum());
    if (hasCurPlayerNum()) {
      result = result && (getCurPlayerNum()
          == other.getCurPlayerNum());
    }
    result = result && (hasMaxPlayerNum() == other.hasMaxPlayerNum());
    if (hasMaxPlayerNum()) {
      result = result && (getMaxPlayerNum()
          == other.getMaxPlayerNum());
    }
    result = result && (hasIsNeedPassword() == other.hasIsNeedPassword());
    if (hasIsNeedPassword()) {
      result = result && (getIsNeedPassword()
          == other.getIsNeedPassword());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasLevel()) {
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
    }
    if (hasThemeId()) {
      hash = (37 * hash) + THEMEID_FIELD_NUMBER;
      hash = (53 * hash) + getThemeId();
    }
    if (hasCurPlayerNum()) {
      hash = (37 * hash) + CURPLAYERNUM_FIELD_NUMBER;
      hash = (53 * hash) + getCurPlayerNum();
    }
    if (hasMaxPlayerNum()) {
      hash = (37 * hash) + MAXPLAYERNUM_FIELD_NUMBER;
      hash = (53 * hash) + getMaxPlayerNum();
    }
    if (hasIsNeedPassword()) {
      hash = (37 * hash) + ISNEEDPASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNeedPassword());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.scene.SceneBriefInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.scene.SceneBriefInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protocols.SceneBriefInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.SceneBriefInfo)
      com.dj.protobuf.scene.SceneBriefInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.scene.Scene.internal_static_Protocols_SceneBriefInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.scene.Scene.internal_static_Protocols_SceneBriefInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.scene.SceneBriefInfo.class, com.dj.protobuf.scene.SceneBriefInfo.Builder.class);
    }

    // Construct using com.dj.protobuf.scene.SceneBriefInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      level_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      themeId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      curPlayerNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      maxPlayerNum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      isNeedPassword_ = false;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.scene.Scene.internal_static_Protocols_SceneBriefInfo_descriptor;
    }

    public com.dj.protobuf.scene.SceneBriefInfo getDefaultInstanceForType() {
      return com.dj.protobuf.scene.SceneBriefInfo.getDefaultInstance();
    }

    public com.dj.protobuf.scene.SceneBriefInfo build() {
      com.dj.protobuf.scene.SceneBriefInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.scene.SceneBriefInfo buildPartial() {
      com.dj.protobuf.scene.SceneBriefInfo result = new com.dj.protobuf.scene.SceneBriefInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.level_ = level_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.themeId_ = themeId_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.curPlayerNum_ = curPlayerNum_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.maxPlayerNum_ = maxPlayerNum_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.isNeedPassword_ = isNeedPassword_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.scene.SceneBriefInfo) {
        return mergeFrom((com.dj.protobuf.scene.SceneBriefInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.scene.SceneBriefInfo other) {
      if (other == com.dj.protobuf.scene.SceneBriefInfo.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasLevel()) {
        setLevel(other.getLevel());
      }
      if (other.hasThemeId()) {
        setThemeId(other.getThemeId());
      }
      if (other.hasCurPlayerNum()) {
        setCurPlayerNum(other.getCurPlayerNum());
      }
      if (other.hasMaxPlayerNum()) {
        setMaxPlayerNum(other.getMaxPlayerNum());
      }
      if (other.hasIsNeedPassword()) {
        setIsNeedPassword(other.getIsNeedPassword());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.scene.SceneBriefInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.scene.SceneBriefInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private int level_ ;
    /**
     * <code>optional int32 level = 4;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 level = 4;</code>
     */
    public int getLevel() {
      return level_;
    }
    /**
     * <code>optional int32 level = 4;</code>
     */
    public Builder setLevel(int value) {
      bitField0_ |= 0x00000004;
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 level = 4;</code>
     */
    public Builder clearLevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      level_ = 0;
      onChanged();
      return this;
    }

    private int themeId_ ;
    /**
     * <code>optional int32 themeId = 5;</code>
     */
    public boolean hasThemeId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 themeId = 5;</code>
     */
    public int getThemeId() {
      return themeId_;
    }
    /**
     * <code>optional int32 themeId = 5;</code>
     */
    public Builder setThemeId(int value) {
      bitField0_ |= 0x00000008;
      themeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 themeId = 5;</code>
     */
    public Builder clearThemeId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      themeId_ = 0;
      onChanged();
      return this;
    }

    private int curPlayerNum_ ;
    /**
     * <code>optional int32 curPlayerNum = 6;</code>
     */
    public boolean hasCurPlayerNum() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 curPlayerNum = 6;</code>
     */
    public int getCurPlayerNum() {
      return curPlayerNum_;
    }
    /**
     * <code>optional int32 curPlayerNum = 6;</code>
     */
    public Builder setCurPlayerNum(int value) {
      bitField0_ |= 0x00000010;
      curPlayerNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 curPlayerNum = 6;</code>
     */
    public Builder clearCurPlayerNum() {
      bitField0_ = (bitField0_ & ~0x00000010);
      curPlayerNum_ = 0;
      onChanged();
      return this;
    }

    private int maxPlayerNum_ ;
    /**
     * <code>optional int32 maxPlayerNum = 7;</code>
     */
    public boolean hasMaxPlayerNum() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 maxPlayerNum = 7;</code>
     */
    public int getMaxPlayerNum() {
      return maxPlayerNum_;
    }
    /**
     * <code>optional int32 maxPlayerNum = 7;</code>
     */
    public Builder setMaxPlayerNum(int value) {
      bitField0_ |= 0x00000020;
      maxPlayerNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 maxPlayerNum = 7;</code>
     */
    public Builder clearMaxPlayerNum() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxPlayerNum_ = 0;
      onChanged();
      return this;
    }

    private boolean isNeedPassword_ ;
    /**
     * <code>optional bool isNeedPassword = 8;</code>
     */
    public boolean hasIsNeedPassword() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool isNeedPassword = 8;</code>
     */
    public boolean getIsNeedPassword() {
      return isNeedPassword_;
    }
    /**
     * <code>optional bool isNeedPassword = 8;</code>
     */
    public Builder setIsNeedPassword(boolean value) {
      bitField0_ |= 0x00000040;
      isNeedPassword_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isNeedPassword = 8;</code>
     */
    public Builder clearIsNeedPassword() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isNeedPassword_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.SceneBriefInfo)
  }

  // @@protoc_insertion_point(class_scope:Protocols.SceneBriefInfo)
  private static final com.dj.protobuf.scene.SceneBriefInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.scene.SceneBriefInfo();
  }

  public static com.dj.protobuf.scene.SceneBriefInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SceneBriefInfo>
      PARSER = new com.google.protobuf.AbstractParser<SceneBriefInfo>() {
    public SceneBriefInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SceneBriefInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SceneBriefInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SceneBriefInfo> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.scene.SceneBriefInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

