// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Scene.proto

package com.dj.protobuf.scene;

public final class Scene {
  private Scene() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneBriefInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneBriefInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_OtomeVector3D_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_OtomeVector3D_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneRoleSkillStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneRoleSkillStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneRoleInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneRoleInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneDetailInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneDetailInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ListSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ListSceneReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ListSceneRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ListSceneRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneBriefInfoNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneBriefInfoNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_JoinSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_JoinSceneReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_JoinSceneRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_JoinSceneRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_JoinSceneNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_JoinSceneNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneDetailInfoNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneDetailInfoNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_LeaveSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_LeaveSceneReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_LeaveSceneRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_LeaveSceneRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_LeaveSceneNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_LeaveSceneNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneMovementReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneMovementReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneMovementRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneMovementRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneMovementNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneMovementNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneUseSkillReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneUseSkillReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneUseSkillRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneUseSkillRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneUseSkillNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneUseSkillNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneCell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneCell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_SceneMapNtf_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_SceneMapNtf_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ScenePosReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ScenePosReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ScenePosRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ScenePosRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ScenePosRsp_PosEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ScenePosRsp_PosEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ScenePosUpdateReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ScenePosUpdateReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ScenePosUpdateRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ScenePosUpdateRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_CheckSceneReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_CheckSceneReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_CheckSceneRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_CheckSceneRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Scene.proto\022\tProtocols\032\rErrorID.proto\032" +
      "\016DateTime.proto\032\022CommonDefine.proto\"\216\001\n\016" +
      "SceneBriefInfo\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\003 \001(\t" +
      "\022\r\n\005level\030\004 \001(\005\022\017\n\007themeId\030\005 \001(\005\022\024\n\014curP" +
      "layerNum\030\006 \001(\005\022\024\n\014maxPlayerNum\030\007 \001(\005\022\026\n\016" +
      "isNeedPassword\030\010 \001(\010\"0\n\rOtomeVector3D\022\t\n" +
      "\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005\"\350\001\n\024Scene" +
      "RoleSkillStatus\022\017\n\007skillId\030\001 \001(\005\022\021\n\tsrcR" +
      "oleId\030\002 \001(\004\022\024\n\014targetRoleId\030\003 \001(\004\022+\n\004typ" +
      "e\030\004 \001(\0162\035.Protocols.ESceneUseSkillType\0222",
      "\n\020srcRoleDirection\030\005 \001(\0132\030.Protocols.Oto" +
      "meVector3D\0225\n\023targetRoleDirection\030\006 \001(\0132" +
      "\030.Protocols.OtomeVector3D\"\340\002\n\rSceneRoleI" +
      "nfo\022-\n\014roleBaseInfo\030\001 \001(\0132\027.Protocols.Ba" +
      "seRoleInfo\022\024\n\014SceneClothes\030\002 \003(\005\022\'\n\004post" +
      "\030\003 \001(\0162\031.Protocols.ESceneRolePost\022\'\n\natt" +
      "endTime\030\004 \001(\0132\023.Protocols.DateTime\022*\n\010po" +
      "sition\030\005 \001(\0132\030.Protocols.OtomeVector3D\022+" +
      "\n\tdirection\030\006 \001(\0132\030.Protocols.OtomeVecto" +
      "r3D\0224\n\013skillStatus\030\007 \001(\0132\037.Protocols.Sce",
      "neRoleSkillStatus\022)\n\014doubleExpire\030\010 \001(\0132" +
      "\023.Protocols.DateTime\"l\n\017SceneDetailInfo\022" +
      ",\n\tbriefInfo\030\001 \001(\0132\031.Protocols.SceneBrie" +
      "fInfo\022+\n\tattenders\030\002 \003(\0132\030.Protocols.Sce" +
      "neRoleInfo\"\016\n\014ListSceneReq\"\\\n\014ListSceneR" +
      "sp\022\031\n\007errorID\030\001 \001(\0162\010.ErrorID\0221\n\016persona" +
      "lScenes\030\002 \003(\0132\031.Protocols.SceneBriefInfo" +
      "\">\n\021SceneBriefInfoNtf\022)\n\006scenes\030\001 \003(\0132\031." +
      "Protocols.SceneBriefInfo\"U\n\014JoinSceneReq" +
      "\022\n\n\002id\030\001 \001(\004\022\020\n\010password\030\002 \001(\t\022\'\n\003pos\030\003 ",
      "\001(\0162\032.Protocols.ESceneRebornPos\"\252\001\n\014Join" +
      "SceneRsp\022\031\n\007errorID\030\001 \001(\0162\010.ErrorID\022$\n\003r" +
      "eq\030\002 \001(\0132\027.Protocols.JoinSceneReq\022.\n\ndet" +
      "ailInfo\030\003 \001(\0132\032.Protocols.SceneDetailInf" +
      "o\022\021\n\tfirstFlag\030\004 \001(\010\022\026\n\016resetCountDown\030\005" +
      " \001(\005\">\n\014JoinSceneNtf\022.\n\014joinRoleInfo\030\001 \001" +
      "(\0132\030.Protocols.SceneRoleInfo\"D\n\022SceneDet" +
      "ailInfoNtf\022.\n\ndetailInfo\030\003 \001(\0132\032.Protoco" +
      "ls.SceneDetailInfo\"\017\n\rLeaveSceneReq\"*\n\rL" +
      "eaveSceneRsp\022\031\n\007errorID\030\001 \001(\0162\010.ErrorID\"",
      "0\n\rLeaveSceneNtf\022\016\n\006roleId\030\001 \001(\004\022\017\n\007scen" +
      "eId\030\002 \001(\004\"\242\001\n\020SceneMovementReq\022+\n\010moveTy" +
      "pe\030\001 \001(\0162\031.Protocols.ESceneMoveType\022%\n\003p" +
      "os\030\002 \001(\0132\030.Protocols.OtomeVector3D\022\r\n\005sp" +
      "eed\030\003 \001(\002\022+\n\tdirection\030\004 \001(\0132\030.Protocols" +
      ".OtomeVector3D\"-\n\020SceneMovementRsp\022\031\n\007er" +
      "rorID\030\001 \001(\0162\010.ErrorID\"\262\001\n\020SceneMovementN" +
      "tf\022\016\n\006roleId\030\001 \001(\004\022+\n\010moveType\030\002 \001(\0162\031.P" +
      "rotocols.ESceneMoveType\022%\n\003pos\030\003 \001(\0132\030.P" +
      "rotocols.OtomeVector3D\022\r\n\005speed\030\004 \001(\002\022+\n",
      "\tdirection\030\005 \001(\0132\030.Protocols.OtomeVector" +
      "3D\"\222\002\n\020SceneUseSkillReq\022\017\n\007skillId\030\001 \001(\005" +
      "\022\024\n\014targetRoleId\030\002 \001(\004\022+\n\004type\030\003 \001(\0162\035.P" +
      "rotocols.ESceneUseSkillType\0222\n\020srcRoleDi" +
      "rection\030\004 \001(\0132\030.Protocols.OtomeVector3D\022" +
      "5\n\023targetRoleDirection\030\005 \001(\0132\030.Protocols" +
      ".OtomeVector3D\022\022\n\nskillCount\030\006 \001(\005\022+\n\tta" +
      "rgetPos\030\007 \001(\0132\030.Protocols.OtomeVector3D\"" +
      "W\n\020SceneUseSkillRsp\022\031\n\007errorID\030\001 \001(\0162\010.E" +
      "rrorID\022(\n\003req\030\002 \001(\0132\033.Protocols.SceneUse",
      "SkillReq\"\204\003\n\020SceneUseSkillNtf\022\017\n\007skillId" +
      "\030\001 \001(\005\022\024\n\014targetRoleId\030\002 \001(\004\022\021\n\tsrcRoleI" +
      "d\030\003 \001(\004\022/\n\rtargetRolePos\030\004 \001(\0132\030.Protoco" +
      "ls.OtomeVector3D\022+\n\004type\030\005 \001(\0162\035.Protoco" +
      "ls.ESceneUseSkillType\022,\n\nscrRolePos\030\006 \001(" +
      "\0132\030.Protocols.OtomeVector3D\0222\n\020srcRoleDi" +
      "rection\030\007 \001(\0132\030.Protocols.OtomeVector3D\022" +
      "5\n\023targetRoleDirection\030\010 \001(\0132\030.Protocols" +
      ".OtomeVector3D\022\022\n\nskillCount\030\t \001(\005\022+\n\tta" +
      "rgetPos\030\n \001(\0132\030.Protocols.OtomeVector3D\"",
      "x\n\tSceneCell\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\'\n\004ty" +
      "pe\030\003 \001(\0162\031.Protocols.ESceneCellType\022\r\n\005s" +
      "tage\030\004 \001(\005\022\016\n\006isShow\030\005 \001(\010\022\r\n\005robId\030\006 \001(" +
      "\005\"\\\n\013SceneMapNtf\022#\n\005cells\030\001 \003(\0132\024.Protoc" +
      "ols.SceneCell\022(\n\004type\030\002 \001(\0162\032.Protocols." +
      "SceneUpdateType\"\035\n\013ScenePosReq\022\016\n\006roleId" +
      "\030\001 \001(\004\"\301\001\n\013ScenePosRsp\022\031\n\007errorID\030\001 \001(\0162" +
      "\010.ErrorID\022,\n\003pos\030\002 \003(\0132\037.Protocols.Scene" +
      "PosRsp.PosEntry\022#\n\003req\030\003 \001(\0132\026.Protocols" +
      ".ScenePosReq\032D\n\010PosEntry\022\013\n\003key\030\001 \001(\005\022\'\n",
      "\005value\030\002 \001(\0132\030.Protocols.OtomeVector3D:\002" +
      "8\001\"5\n\021ScenePosUpdateReq\022\n\n\002id\030\001 \001(\005\022\t\n\001x" +
      "\030\002 \001(\005\022\t\n\001y\030\003 \001(\005\".\n\021ScenePosUpdateRsp\022\031" +
      "\n\007errorID\030\001 \001(\0162\010.ErrorID\"\017\n\rCheckSceneR" +
      "eq\"\204\001\n\rCheckSceneRsp\022\031\n\007errorID\030\001 \001(\0162\010." +
      "ErrorID\0223\n\017sceneDetailInfo\030\002 \001(\0132\032.Proto" +
      "cols.SceneDetailInfo\022#\n\005cells\030\003 \003(\0132\024.Pr" +
      "otocols.SceneCell*;\n\016ESceneMoveType\022\r\n\tM" +
      "ov_Start\020\001\022\014\n\010Mov_Stop\020\002\022\014\n\010Mov_Sync\020\003*&" +
      "\n\016ESceneRolePost\022\t\n\005Owner\020\001\022\t\n\005Guest\020\002*7",
      "\n\022ESceneUseSkillType\022\017\n\013Skill_Start\020\001\022\020\n" +
      "\014Skill_Cancel\020\002*\214\001\n\017ESceneRebornPos\022\r\n\tR" +
      "ebornPos\020\000\022\020\n\nRebornPos1\020\311\323\006\022\020\n\nRebornPo" +
      "s2\020\312\323\006\022\020\n\nRebornPos3\020\313\323\006\022\020\n\nRebornPos4\020\314" +
      "\323\006\022\020\n\nRebornPos5\020\315\323\006\022\020\n\nRebornPos6\020\316\323\006*\344" +
      "\003\n\016ESceneCellType\022\022\n\005Empty\020\377\377\377\377\377\377\377\377\377\001\022\013\n" +
      "\007Unknown\020\000\022\n\n\004Coal\020\211\225\006\022\n\n\004Iron\020\212\225\006\022\021\n\013Si" +
      "lver_Mine\020\213\225\006\022\017\n\tGold_Mine\020\214\225\006\022\n\n\004Soil\020\215" +
      "\225\006\022\013\n\005Stone\020\216\225\006\022\017\n\tElement_1\020\361\234\006\022\017\n\tElem" +
      "ent_2\020\362\234\006\022\017\n\tElement_3\020\363\234\006\022\017\n\tElement_4\020",
      "\364\234\006\022\017\n\tElement_5\020\365\234\006\022\013\n\005Egg_1\020\331\244\006\022\013\n\005Egg" +
      "_2\020\332\244\006\022\013\n\005Egg_3\020\333\244\006\022\013\n\005Egg_4\020\334\244\006\022\034\n\026frie" +
      "nd_right_position1\020\311\323\006\022\033\n\025friend_left_po" +
      "sition2\020\312\323\006\022\034\n\026friend_right_position3\020\313\323" +
      "\006\022\033\n\025friend_left_position4\020\314\323\006\022\034\n\026friend" +
      "_right_position5\020\315\323\006\022\033\n\025friend_left_posi" +
      "tion6\020\316\323\006\022\017\n\tMap_Piece\020\301\254\006\022\021\n\013Rob_Diamon" +
      "d\020\251\264\006B\031\n\025com.dj.protobuf.sceneP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dj.protobuf.ErrorIDOuterClass.getDescriptor(),
          com.dj.protobuf.datetime.DateTimeOuterClass.getDescriptor(),
          com.dj.protobuf.common.CommonDefine.getDescriptor(),
        }, assigner);
    internal_static_Protocols_SceneBriefInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocols_SceneBriefInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneBriefInfo_descriptor,
        new java.lang.String[] { "Id", "Name", "Level", "ThemeId", "CurPlayerNum", "MaxPlayerNum", "IsNeedPassword", });
    internal_static_Protocols_OtomeVector3D_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protocols_OtomeVector3D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_OtomeVector3D_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_Protocols_SceneRoleSkillStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protocols_SceneRoleSkillStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneRoleSkillStatus_descriptor,
        new java.lang.String[] { "SkillId", "SrcRoleId", "TargetRoleId", "Type", "SrcRoleDirection", "TargetRoleDirection", });
    internal_static_Protocols_SceneRoleInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Protocols_SceneRoleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneRoleInfo_descriptor,
        new java.lang.String[] { "RoleBaseInfo", "SceneClothes", "Post", "AttendTime", "Position", "Direction", "SkillStatus", "DoubleExpire", });
    internal_static_Protocols_SceneDetailInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Protocols_SceneDetailInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneDetailInfo_descriptor,
        new java.lang.String[] { "BriefInfo", "Attenders", });
    internal_static_Protocols_ListSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Protocols_ListSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ListSceneReq_descriptor,
        new java.lang.String[] { });
    internal_static_Protocols_ListSceneRsp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Protocols_ListSceneRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ListSceneRsp_descriptor,
        new java.lang.String[] { "ErrorID", "PersonalScenes", });
    internal_static_Protocols_SceneBriefInfoNtf_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Protocols_SceneBriefInfoNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneBriefInfoNtf_descriptor,
        new java.lang.String[] { "Scenes", });
    internal_static_Protocols_JoinSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Protocols_JoinSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_JoinSceneReq_descriptor,
        new java.lang.String[] { "Id", "Password", "Pos", });
    internal_static_Protocols_JoinSceneRsp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Protocols_JoinSceneRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_JoinSceneRsp_descriptor,
        new java.lang.String[] { "ErrorID", "Req", "DetailInfo", "FirstFlag", "ResetCountDown", });
    internal_static_Protocols_JoinSceneNtf_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Protocols_JoinSceneNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_JoinSceneNtf_descriptor,
        new java.lang.String[] { "JoinRoleInfo", });
    internal_static_Protocols_SceneDetailInfoNtf_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Protocols_SceneDetailInfoNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneDetailInfoNtf_descriptor,
        new java.lang.String[] { "DetailInfo", });
    internal_static_Protocols_LeaveSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Protocols_LeaveSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_LeaveSceneReq_descriptor,
        new java.lang.String[] { });
    internal_static_Protocols_LeaveSceneRsp_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Protocols_LeaveSceneRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_LeaveSceneRsp_descriptor,
        new java.lang.String[] { "ErrorID", });
    internal_static_Protocols_LeaveSceneNtf_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Protocols_LeaveSceneNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_LeaveSceneNtf_descriptor,
        new java.lang.String[] { "RoleId", "SceneId", });
    internal_static_Protocols_SceneMovementReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Protocols_SceneMovementReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneMovementReq_descriptor,
        new java.lang.String[] { "MoveType", "Pos", "Speed", "Direction", });
    internal_static_Protocols_SceneMovementRsp_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Protocols_SceneMovementRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneMovementRsp_descriptor,
        new java.lang.String[] { "ErrorID", });
    internal_static_Protocols_SceneMovementNtf_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Protocols_SceneMovementNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneMovementNtf_descriptor,
        new java.lang.String[] { "RoleId", "MoveType", "Pos", "Speed", "Direction", });
    internal_static_Protocols_SceneUseSkillReq_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Protocols_SceneUseSkillReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneUseSkillReq_descriptor,
        new java.lang.String[] { "SkillId", "TargetRoleId", "Type", "SrcRoleDirection", "TargetRoleDirection", "SkillCount", "TargetPos", });
    internal_static_Protocols_SceneUseSkillRsp_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Protocols_SceneUseSkillRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneUseSkillRsp_descriptor,
        new java.lang.String[] { "ErrorID", "Req", });
    internal_static_Protocols_SceneUseSkillNtf_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Protocols_SceneUseSkillNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneUseSkillNtf_descriptor,
        new java.lang.String[] { "SkillId", "TargetRoleId", "SrcRoleId", "TargetRolePos", "Type", "ScrRolePos", "SrcRoleDirection", "TargetRoleDirection", "SkillCount", "TargetPos", });
    internal_static_Protocols_SceneCell_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Protocols_SceneCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneCell_descriptor,
        new java.lang.String[] { "X", "Y", "Type", "Stage", "IsShow", "RobId", });
    internal_static_Protocols_SceneMapNtf_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Protocols_SceneMapNtf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_SceneMapNtf_descriptor,
        new java.lang.String[] { "Cells", "Type", });
    internal_static_Protocols_ScenePosReq_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Protocols_ScenePosReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ScenePosReq_descriptor,
        new java.lang.String[] { "RoleId", });
    internal_static_Protocols_ScenePosRsp_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Protocols_ScenePosRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ScenePosRsp_descriptor,
        new java.lang.String[] { "ErrorID", "Pos", "Req", });
    internal_static_Protocols_ScenePosRsp_PosEntry_descriptor =
      internal_static_Protocols_ScenePosRsp_descriptor.getNestedTypes().get(0);
    internal_static_Protocols_ScenePosRsp_PosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ScenePosRsp_PosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Protocols_ScenePosUpdateReq_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Protocols_ScenePosUpdateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ScenePosUpdateReq_descriptor,
        new java.lang.String[] { "Id", "X", "Y", });
    internal_static_Protocols_ScenePosUpdateRsp_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Protocols_ScenePosUpdateRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ScenePosUpdateRsp_descriptor,
        new java.lang.String[] { "ErrorID", });
    internal_static_Protocols_CheckSceneReq_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Protocols_CheckSceneReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_CheckSceneReq_descriptor,
        new java.lang.String[] { });
    internal_static_Protocols_CheckSceneRsp_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Protocols_CheckSceneRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_CheckSceneRsp_descriptor,
        new java.lang.String[] { "ErrorID", "SceneDetailInfo", "Cells", });
    com.dj.protobuf.ErrorIDOuterClass.getDescriptor();
    com.dj.protobuf.datetime.DateTimeOuterClass.getDescriptor();
    com.dj.protobuf.common.CommonDefine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
