// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mall.proto

package com.dj.protobuf.mall;

public interface ExchangeGoodsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.ExchangeGoodsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ExchangeMall 中的序号
   * </pre>
   *
   * <code>optional int32 index = 1;</code>
   */
  boolean hasIndex();
  /**
   * <pre>
   * ExchangeMall 中的序号
   * </pre>
   *
   * <code>optional int32 index = 1;</code>
   */
  int getIndex();

  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 购买几份
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>optional int32 packageNum = 2;</code>
   */
  boolean hasPackageNum();
  /**
   * <pre>
   *&#47; &lt;summary&gt;
   * / 购买几份
   * / &lt;/summary&gt;
   * </pre>
   *
   * <code>optional int32 packageNum = 2;</code>
   */
  int getPackageNum();
}
