// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Obstacle.proto

package com.dj.protobuf.obstacle;

public final class Obstacle {
  private Obstacle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ObstaclesListReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ObstaclesListReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ObstaclesListRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ObstaclesListRsp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ObstaclesListRsp_LandEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ObstaclesListRsp_LandEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ObstaclesOpenupReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ObstaclesOpenupReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protocols_ObstaclesOpenupRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protocols_ObstaclesOpenupRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Obstacle.proto\022\tProtocols\032\rErrorID.pro" +
      "to\"\"\n\020ObstaclesListReq\022\016\n\006roleId\030\001 \001(\004\"\271" +
      "\001\n\020ObstaclesListRsp\022\031\n\007errorID\030\001 \001(\0162\010.E" +
      "rrorID\022(\n\003req\030\002 \001(\0132\033.Protocols.Obstacle" +
      "sListReq\0223\n\004land\030\003 \003(\0132%.Protocols.Obsta" +
      "clesListRsp.LandEntry\032+\n\tLandEntry\022\013\n\003ke" +
      "y\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\"#\n\022ObstaclesO" +
      "penupReq\022\r\n\005index\030\001 \001(\005\"[\n\022ObstaclesOpen" +
      "upRsp\022\031\n\007errorID\030\001 \001(\0162\010.ErrorID\022*\n\003req\030" +
      "\002 \001(\0132\035.Protocols.ObstaclesOpenupReqB\034\n\030",
      "com.dj.protobuf.obstacleP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dj.protobuf.ErrorIDOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Protocols_ObstaclesListReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protocols_ObstaclesListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ObstaclesListReq_descriptor,
        new java.lang.String[] { "RoleId", });
    internal_static_Protocols_ObstaclesListRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protocols_ObstaclesListRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ObstaclesListRsp_descriptor,
        new java.lang.String[] { "ErrorID", "Req", "Land", });
    internal_static_Protocols_ObstaclesListRsp_LandEntry_descriptor =
      internal_static_Protocols_ObstaclesListRsp_descriptor.getNestedTypes().get(0);
    internal_static_Protocols_ObstaclesListRsp_LandEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ObstaclesListRsp_LandEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Protocols_ObstaclesOpenupReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protocols_ObstaclesOpenupReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ObstaclesOpenupReq_descriptor,
        new java.lang.String[] { "Index", });
    internal_static_Protocols_ObstaclesOpenupRsp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Protocols_ObstaclesOpenupRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protocols_ObstaclesOpenupRsp_descriptor,
        new java.lang.String[] { "ErrorID", "Req", });
    com.dj.protobuf.ErrorIDOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
