// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowTable.proto

package com.dj.protobuf.showtable;

/**
 * <pre>
 * 合成
 * </pre>
 *
 * Protobuf type {@code Protocols.AntiqueComposeReq}
 */
public  final class AntiqueComposeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.AntiqueComposeReq)
    AntiqueComposeReqOrBuilder {
  // Use AntiqueComposeReq.newBuilder() to construct.
  private AntiqueComposeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AntiqueComposeReq() {
    type_ = 0;
    materials_ = java.util.Collections.emptyList();
    page_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AntiqueComposeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            type_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              materials_ = new java.util.ArrayList<com.dj.protobuf.showtable.Antique>();
              mutable_bitField0_ |= 0x00000002;
            }
            materials_.add(
                input.readMessage(com.dj.protobuf.showtable.Antique.PARSER, extensionRegistry));
            break;
          }
          case 26: {
            com.dj.protobuf.showtable.ShowTableItem.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = targetId_.toBuilder();
            }
            targetId_ = input.readMessage(com.dj.protobuf.showtable.ShowTableItem.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(targetId_);
              targetId_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            page_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        materials_ = java.util.Collections.unmodifiableList(materials_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_AntiqueComposeReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_AntiqueComposeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.showtable.AntiqueComposeReq.class, com.dj.protobuf.showtable.AntiqueComposeReq.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional int32 type = 1;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int MATERIALS_FIELD_NUMBER = 2;
  private java.util.List<com.dj.protobuf.showtable.Antique> materials_;
  /**
   * <code>repeated .Protocols.Antique materials = 2;</code>
   */
  public java.util.List<com.dj.protobuf.showtable.Antique> getMaterialsList() {
    return materials_;
  }
  /**
   * <code>repeated .Protocols.Antique materials = 2;</code>
   */
  public java.util.List<? extends com.dj.protobuf.showtable.AntiqueOrBuilder> 
      getMaterialsOrBuilderList() {
    return materials_;
  }
  /**
   * <code>repeated .Protocols.Antique materials = 2;</code>
   */
  public int getMaterialsCount() {
    return materials_.size();
  }
  /**
   * <code>repeated .Protocols.Antique materials = 2;</code>
   */
  public com.dj.protobuf.showtable.Antique getMaterials(int index) {
    return materials_.get(index);
  }
  /**
   * <code>repeated .Protocols.Antique materials = 2;</code>
   */
  public com.dj.protobuf.showtable.AntiqueOrBuilder getMaterialsOrBuilder(
      int index) {
    return materials_.get(index);
  }

  public static final int TARGETID_FIELD_NUMBER = 3;
  private com.dj.protobuf.showtable.ShowTableItem targetId_;
  /**
   * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
   */
  public boolean hasTargetId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
   */
  public com.dj.protobuf.showtable.ShowTableItem getTargetId() {
    return targetId_ == null ? com.dj.protobuf.showtable.ShowTableItem.getDefaultInstance() : targetId_;
  }
  /**
   * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
   */
  public com.dj.protobuf.showtable.ShowTableItemOrBuilder getTargetIdOrBuilder() {
    return targetId_ == null ? com.dj.protobuf.showtable.ShowTableItem.getDefaultInstance() : targetId_;
  }

  public static final int PAGE_FIELD_NUMBER = 4;
  private int page_;
  /**
   * <code>optional int32 page = 4;</code>
   */
  public boolean hasPage() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 page = 4;</code>
   */
  public int getPage() {
    return page_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, type_);
    }
    for (int i = 0; i < materials_.size(); i++) {
      output.writeMessage(2, materials_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(3, getTargetId());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(4, page_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    for (int i = 0; i < materials_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, materials_.get(i));
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTargetId());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, page_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.showtable.AntiqueComposeReq)) {
      return super.equals(obj);
    }
    com.dj.protobuf.showtable.AntiqueComposeReq other = (com.dj.protobuf.showtable.AntiqueComposeReq) obj;

    boolean result = true;
    result = result && (hasType() == other.hasType());
    if (hasType()) {
      result = result && (getType()
          == other.getType());
    }
    result = result && getMaterialsList()
        .equals(other.getMaterialsList());
    result = result && (hasTargetId() == other.hasTargetId());
    if (hasTargetId()) {
      result = result && getTargetId()
          .equals(other.getTargetId());
    }
    result = result && (hasPage() == other.hasPage());
    if (hasPage()) {
      result = result && (getPage()
          == other.getPage());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
    }
    if (getMaterialsCount() > 0) {
      hash = (37 * hash) + MATERIALS_FIELD_NUMBER;
      hash = (53 * hash) + getMaterialsList().hashCode();
    }
    if (hasTargetId()) {
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId().hashCode();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.AntiqueComposeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.showtable.AntiqueComposeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 合成
   * </pre>
   *
   * Protobuf type {@code Protocols.AntiqueComposeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.AntiqueComposeReq)
      com.dj.protobuf.showtable.AntiqueComposeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_AntiqueComposeReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_AntiqueComposeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.showtable.AntiqueComposeReq.class, com.dj.protobuf.showtable.AntiqueComposeReq.Builder.class);
    }

    // Construct using com.dj.protobuf.showtable.AntiqueComposeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMaterialsFieldBuilder();
        getTargetIdFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (materialsBuilder_ == null) {
        materials_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        materialsBuilder_.clear();
      }
      if (targetIdBuilder_ == null) {
        targetId_ = null;
      } else {
        targetIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_AntiqueComposeReq_descriptor;
    }

    public com.dj.protobuf.showtable.AntiqueComposeReq getDefaultInstanceForType() {
      return com.dj.protobuf.showtable.AntiqueComposeReq.getDefaultInstance();
    }

    public com.dj.protobuf.showtable.AntiqueComposeReq build() {
      com.dj.protobuf.showtable.AntiqueComposeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.showtable.AntiqueComposeReq buildPartial() {
      com.dj.protobuf.showtable.AntiqueComposeReq result = new com.dj.protobuf.showtable.AntiqueComposeReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (materialsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          materials_ = java.util.Collections.unmodifiableList(materials_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.materials_ = materials_;
      } else {
        result.materials_ = materialsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000002;
      }
      if (targetIdBuilder_ == null) {
        result.targetId_ = targetId_;
      } else {
        result.targetId_ = targetIdBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000004;
      }
      result.page_ = page_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.showtable.AntiqueComposeReq) {
        return mergeFrom((com.dj.protobuf.showtable.AntiqueComposeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.showtable.AntiqueComposeReq other) {
      if (other == com.dj.protobuf.showtable.AntiqueComposeReq.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (materialsBuilder_ == null) {
        if (!other.materials_.isEmpty()) {
          if (materials_.isEmpty()) {
            materials_ = other.materials_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMaterialsIsMutable();
            materials_.addAll(other.materials_);
          }
          onChanged();
        }
      } else {
        if (!other.materials_.isEmpty()) {
          if (materialsBuilder_.isEmpty()) {
            materialsBuilder_.dispose();
            materialsBuilder_ = null;
            materials_ = other.materials_;
            bitField0_ = (bitField0_ & ~0x00000002);
            materialsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMaterialsFieldBuilder() : null;
          } else {
            materialsBuilder_.addAllMessages(other.materials_);
          }
        }
      }
      if (other.hasTargetId()) {
        mergeTargetId(other.getTargetId());
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.showtable.AntiqueComposeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.showtable.AntiqueComposeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <code>optional int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000001;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.dj.protobuf.showtable.Antique> materials_ =
      java.util.Collections.emptyList();
    private void ensureMaterialsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        materials_ = new java.util.ArrayList<com.dj.protobuf.showtable.Antique>(materials_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dj.protobuf.showtable.Antique, com.dj.protobuf.showtable.Antique.Builder, com.dj.protobuf.showtable.AntiqueOrBuilder> materialsBuilder_;

    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public java.util.List<com.dj.protobuf.showtable.Antique> getMaterialsList() {
      if (materialsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(materials_);
      } else {
        return materialsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public int getMaterialsCount() {
      if (materialsBuilder_ == null) {
        return materials_.size();
      } else {
        return materialsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public com.dj.protobuf.showtable.Antique getMaterials(int index) {
      if (materialsBuilder_ == null) {
        return materials_.get(index);
      } else {
        return materialsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder setMaterials(
        int index, com.dj.protobuf.showtable.Antique value) {
      if (materialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaterialsIsMutable();
        materials_.set(index, value);
        onChanged();
      } else {
        materialsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder setMaterials(
        int index, com.dj.protobuf.showtable.Antique.Builder builderForValue) {
      if (materialsBuilder_ == null) {
        ensureMaterialsIsMutable();
        materials_.set(index, builderForValue.build());
        onChanged();
      } else {
        materialsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder addMaterials(com.dj.protobuf.showtable.Antique value) {
      if (materialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaterialsIsMutable();
        materials_.add(value);
        onChanged();
      } else {
        materialsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder addMaterials(
        int index, com.dj.protobuf.showtable.Antique value) {
      if (materialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMaterialsIsMutable();
        materials_.add(index, value);
        onChanged();
      } else {
        materialsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder addMaterials(
        com.dj.protobuf.showtable.Antique.Builder builderForValue) {
      if (materialsBuilder_ == null) {
        ensureMaterialsIsMutable();
        materials_.add(builderForValue.build());
        onChanged();
      } else {
        materialsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder addMaterials(
        int index, com.dj.protobuf.showtable.Antique.Builder builderForValue) {
      if (materialsBuilder_ == null) {
        ensureMaterialsIsMutable();
        materials_.add(index, builderForValue.build());
        onChanged();
      } else {
        materialsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder addAllMaterials(
        java.lang.Iterable<? extends com.dj.protobuf.showtable.Antique> values) {
      if (materialsBuilder_ == null) {
        ensureMaterialsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, materials_);
        onChanged();
      } else {
        materialsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder clearMaterials() {
      if (materialsBuilder_ == null) {
        materials_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        materialsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public Builder removeMaterials(int index) {
      if (materialsBuilder_ == null) {
        ensureMaterialsIsMutable();
        materials_.remove(index);
        onChanged();
      } else {
        materialsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public com.dj.protobuf.showtable.Antique.Builder getMaterialsBuilder(
        int index) {
      return getMaterialsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public com.dj.protobuf.showtable.AntiqueOrBuilder getMaterialsOrBuilder(
        int index) {
      if (materialsBuilder_ == null) {
        return materials_.get(index);  } else {
        return materialsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public java.util.List<? extends com.dj.protobuf.showtable.AntiqueOrBuilder> 
         getMaterialsOrBuilderList() {
      if (materialsBuilder_ != null) {
        return materialsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(materials_);
      }
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public com.dj.protobuf.showtable.Antique.Builder addMaterialsBuilder() {
      return getMaterialsFieldBuilder().addBuilder(
          com.dj.protobuf.showtable.Antique.getDefaultInstance());
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public com.dj.protobuf.showtable.Antique.Builder addMaterialsBuilder(
        int index) {
      return getMaterialsFieldBuilder().addBuilder(
          index, com.dj.protobuf.showtable.Antique.getDefaultInstance());
    }
    /**
     * <code>repeated .Protocols.Antique materials = 2;</code>
     */
    public java.util.List<com.dj.protobuf.showtable.Antique.Builder> 
         getMaterialsBuilderList() {
      return getMaterialsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.dj.protobuf.showtable.Antique, com.dj.protobuf.showtable.Antique.Builder, com.dj.protobuf.showtable.AntiqueOrBuilder> 
        getMaterialsFieldBuilder() {
      if (materialsBuilder_ == null) {
        materialsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.dj.protobuf.showtable.Antique, com.dj.protobuf.showtable.Antique.Builder, com.dj.protobuf.showtable.AntiqueOrBuilder>(
                materials_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        materials_ = null;
      }
      return materialsBuilder_;
    }

    private com.dj.protobuf.showtable.ShowTableItem targetId_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.showtable.ShowTableItem, com.dj.protobuf.showtable.ShowTableItem.Builder, com.dj.protobuf.showtable.ShowTableItemOrBuilder> targetIdBuilder_;
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public com.dj.protobuf.showtable.ShowTableItem getTargetId() {
      if (targetIdBuilder_ == null) {
        return targetId_ == null ? com.dj.protobuf.showtable.ShowTableItem.getDefaultInstance() : targetId_;
      } else {
        return targetIdBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public Builder setTargetId(com.dj.protobuf.showtable.ShowTableItem value) {
      if (targetIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        targetId_ = value;
        onChanged();
      } else {
        targetIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public Builder setTargetId(
        com.dj.protobuf.showtable.ShowTableItem.Builder builderForValue) {
      if (targetIdBuilder_ == null) {
        targetId_ = builderForValue.build();
        onChanged();
      } else {
        targetIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public Builder mergeTargetId(com.dj.protobuf.showtable.ShowTableItem value) {
      if (targetIdBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            targetId_ != null &&
            targetId_ != com.dj.protobuf.showtable.ShowTableItem.getDefaultInstance()) {
          targetId_ =
            com.dj.protobuf.showtable.ShowTableItem.newBuilder(targetId_).mergeFrom(value).buildPartial();
        } else {
          targetId_ = value;
        }
        onChanged();
      } else {
        targetIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public Builder clearTargetId() {
      if (targetIdBuilder_ == null) {
        targetId_ = null;
        onChanged();
      } else {
        targetIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public com.dj.protobuf.showtable.ShowTableItem.Builder getTargetIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTargetIdFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    public com.dj.protobuf.showtable.ShowTableItemOrBuilder getTargetIdOrBuilder() {
      if (targetIdBuilder_ != null) {
        return targetIdBuilder_.getMessageOrBuilder();
      } else {
        return targetId_ == null ?
            com.dj.protobuf.showtable.ShowTableItem.getDefaultInstance() : targetId_;
      }
    }
    /**
     * <code>optional .Protocols.ShowTableItem targetId = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.dj.protobuf.showtable.ShowTableItem, com.dj.protobuf.showtable.ShowTableItem.Builder, com.dj.protobuf.showtable.ShowTableItemOrBuilder> 
        getTargetIdFieldBuilder() {
      if (targetIdBuilder_ == null) {
        targetIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.dj.protobuf.showtable.ShowTableItem, com.dj.protobuf.showtable.ShowTableItem.Builder, com.dj.protobuf.showtable.ShowTableItemOrBuilder>(
                getTargetId(),
                getParentForChildren(),
                isClean());
        targetId_ = null;
      }
      return targetIdBuilder_;
    }

    private int page_ ;
    /**
     * <code>optional int32 page = 4;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 page = 4;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>optional int32 page = 4;</code>
     */
    public Builder setPage(int value) {
      bitField0_ |= 0x00000008;
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page = 4;</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      page_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.AntiqueComposeReq)
  }

  // @@protoc_insertion_point(class_scope:Protocols.AntiqueComposeReq)
  private static final com.dj.protobuf.showtable.AntiqueComposeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.showtable.AntiqueComposeReq();
  }

  public static com.dj.protobuf.showtable.AntiqueComposeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AntiqueComposeReq>
      PARSER = new com.google.protobuf.AbstractParser<AntiqueComposeReq>() {
    public AntiqueComposeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AntiqueComposeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AntiqueComposeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AntiqueComposeReq> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.showtable.AntiqueComposeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

