// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowTable.proto

package com.dj.protobuf.showtable;

/**
 * <pre>
 *物品交换位置
 * </pre>
 *
 * Protobuf type {@code Protocols.ShowTableChangePositionReq}
 */
public  final class ShowTableChangePositionReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protocols.ShowTableChangePositionReq)
    ShowTableChangePositionReqOrBuilder {
  // Use ShowTableChangePositionReq.newBuilder() to construct.
  private ShowTableChangePositionReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShowTableChangePositionReq() {
    type_ = 0;
    page_ = 0;
    index1_ = 0;
    index2_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShowTableChangePositionReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            type_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            page_ = input.readInt32();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            index1_ = input.readInt32();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            index2_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_ShowTableChangePositionReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_ShowTableChangePositionReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dj.protobuf.showtable.ShowTableChangePositionReq.class, com.dj.protobuf.showtable.ShowTableChangePositionReq.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional int32 type = 1;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 type = 1;</code>
   */
  public int getType() {
    return type_;
  }

  public static final int PAGE_FIELD_NUMBER = 2;
  private int page_;
  /**
   * <code>optional int32 page = 2;</code>
   */
  public boolean hasPage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 page = 2;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int INDEX1_FIELD_NUMBER = 3;
  private int index1_;
  /**
   * <code>optional int32 index1 = 3;</code>
   */
  public boolean hasIndex1() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int32 index1 = 3;</code>
   */
  public int getIndex1() {
    return index1_;
  }

  public static final int INDEX2_FIELD_NUMBER = 4;
  private int index2_;
  /**
   * <code>optional int32 index2 = 4;</code>
   */
  public boolean hasIndex2() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int32 index2 = 4;</code>
   */
  public int getIndex2() {
    return index2_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, type_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, page_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt32(3, index1_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, index2_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, type_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, page_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, index1_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, index2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dj.protobuf.showtable.ShowTableChangePositionReq)) {
      return super.equals(obj);
    }
    com.dj.protobuf.showtable.ShowTableChangePositionReq other = (com.dj.protobuf.showtable.ShowTableChangePositionReq) obj;

    boolean result = true;
    result = result && (hasType() == other.hasType());
    if (hasType()) {
      result = result && (getType()
          == other.getType());
    }
    result = result && (hasPage() == other.hasPage());
    if (hasPage()) {
      result = result && (getPage()
          == other.getPage());
    }
    result = result && (hasIndex1() == other.hasIndex1());
    if (hasIndex1()) {
      result = result && (getIndex1()
          == other.getIndex1());
    }
    result = result && (hasIndex2() == other.hasIndex2());
    if (hasIndex2()) {
      result = result && (getIndex2()
          == other.getIndex2());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
    }
    if (hasIndex1()) {
      hash = (37 * hash) + INDEX1_FIELD_NUMBER;
      hash = (53 * hash) + getIndex1();
    }
    if (hasIndex2()) {
      hash = (37 * hash) + INDEX2_FIELD_NUMBER;
      hash = (53 * hash) + getIndex2();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dj.protobuf.showtable.ShowTableChangePositionReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dj.protobuf.showtable.ShowTableChangePositionReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *物品交换位置
   * </pre>
   *
   * Protobuf type {@code Protocols.ShowTableChangePositionReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protocols.ShowTableChangePositionReq)
      com.dj.protobuf.showtable.ShowTableChangePositionReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_ShowTableChangePositionReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_ShowTableChangePositionReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dj.protobuf.showtable.ShowTableChangePositionReq.class, com.dj.protobuf.showtable.ShowTableChangePositionReq.Builder.class);
    }

    // Construct using com.dj.protobuf.showtable.ShowTableChangePositionReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      page_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      index1_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      index2_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dj.protobuf.showtable.ShowTable.internal_static_Protocols_ShowTableChangePositionReq_descriptor;
    }

    public com.dj.protobuf.showtable.ShowTableChangePositionReq getDefaultInstanceForType() {
      return com.dj.protobuf.showtable.ShowTableChangePositionReq.getDefaultInstance();
    }

    public com.dj.protobuf.showtable.ShowTableChangePositionReq build() {
      com.dj.protobuf.showtable.ShowTableChangePositionReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dj.protobuf.showtable.ShowTableChangePositionReq buildPartial() {
      com.dj.protobuf.showtable.ShowTableChangePositionReq result = new com.dj.protobuf.showtable.ShowTableChangePositionReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.page_ = page_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.index1_ = index1_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.index2_ = index2_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dj.protobuf.showtable.ShowTableChangePositionReq) {
        return mergeFrom((com.dj.protobuf.showtable.ShowTableChangePositionReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dj.protobuf.showtable.ShowTableChangePositionReq other) {
      if (other == com.dj.protobuf.showtable.ShowTableChangePositionReq.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasPage()) {
        setPage(other.getPage());
      }
      if (other.hasIndex1()) {
        setIndex1(other.getIndex1());
      }
      if (other.hasIndex2()) {
        setIndex2(other.getIndex2());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dj.protobuf.showtable.ShowTableChangePositionReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dj.protobuf.showtable.ShowTableChangePositionReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ ;
    /**
     * <code>optional int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000001;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 1;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private int page_ ;
    /**
     * <code>optional int32 page = 2;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>optional int32 page = 2;</code>
     */
    public Builder setPage(int value) {
      bitField0_ |= 0x00000002;
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 page = 2;</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = 0;
      onChanged();
      return this;
    }

    private int index1_ ;
    /**
     * <code>optional int32 index1 = 3;</code>
     */
    public boolean hasIndex1() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 index1 = 3;</code>
     */
    public int getIndex1() {
      return index1_;
    }
    /**
     * <code>optional int32 index1 = 3;</code>
     */
    public Builder setIndex1(int value) {
      bitField0_ |= 0x00000004;
      index1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 index1 = 3;</code>
     */
    public Builder clearIndex1() {
      bitField0_ = (bitField0_ & ~0x00000004);
      index1_ = 0;
      onChanged();
      return this;
    }

    private int index2_ ;
    /**
     * <code>optional int32 index2 = 4;</code>
     */
    public boolean hasIndex2() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 index2 = 4;</code>
     */
    public int getIndex2() {
      return index2_;
    }
    /**
     * <code>optional int32 index2 = 4;</code>
     */
    public Builder setIndex2(int value) {
      bitField0_ |= 0x00000008;
      index2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 index2 = 4;</code>
     */
    public Builder clearIndex2() {
      bitField0_ = (bitField0_ & ~0x00000008);
      index2_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protocols.ShowTableChangePositionReq)
  }

  // @@protoc_insertion_point(class_scope:Protocols.ShowTableChangePositionReq)
  private static final com.dj.protobuf.showtable.ShowTableChangePositionReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dj.protobuf.showtable.ShowTableChangePositionReq();
  }

  public static com.dj.protobuf.showtable.ShowTableChangePositionReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ShowTableChangePositionReq>
      PARSER = new com.google.protobuf.AbstractParser<ShowTableChangePositionReq>() {
    public ShowTableChangePositionReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowTableChangePositionReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShowTableChangePositionReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShowTableChangePositionReq> getParserForType() {
    return PARSER;
  }

  public com.dj.protobuf.showtable.ShowTableChangePositionReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

