// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rob.proto

package com.dj.protobuf.rob;

public interface RobMapRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.RobMapRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  boolean hasErrorID();
  /**
   * <code>optional .ErrorID errorID = 1;</code>
   */
  com.dj.protobuf.ErrorIDOuterClass.ErrorID getErrorID();

  /**
   * <code>optional int32 actionValue = 2;</code>
   */
  boolean hasActionValue();
  /**
   * <code>optional int32 actionValue = 2;</code>
   */
  int getActionValue();

  /**
   * <pre>
   * 消灭毒虫标记 0未接受，1接受过该任务
   * </pre>
   *
   * <code>optional int32 monsterTask = 3;</code>
   */
  boolean hasMonsterTask();
  /**
   * <pre>
   * 消灭毒虫标记 0未接受，1接受过该任务
   * </pre>
   *
   * <code>optional int32 monsterTask = 3;</code>
   */
  int getMonsterTask();
}
