// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Verify.proto

package com.dj.protobuf.verify;

public interface VerifyHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.VerifyHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 鉴定的物品
   * </pre>
   *
   * <code>optional int32 itemId = 1;</code>
   */
  boolean hasItemId();
  /**
   * <pre>
   * 鉴定的物品
   * </pre>
   *
   * <code>optional int32 itemId = 1;</code>
   */
  int getItemId();

  /**
   * <pre>
   * 鉴定人
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo verifyRoleInfo = 2;</code>
   */
  boolean hasVerifyRoleInfo();
  /**
   * <pre>
   * 鉴定人
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo verifyRoleInfo = 2;</code>
   */
  com.dj.protobuf.common.BaseRoleInfo getVerifyRoleInfo();
  /**
   * <pre>
   * 鉴定人
   * </pre>
   *
   * <code>optional .Protocols.BaseRoleInfo verifyRoleInfo = 2;</code>
   */
  com.dj.protobuf.common.BaseRoleInfoOrBuilder getVerifyRoleInfoOrBuilder();

  /**
   * <pre>
   * 鉴定时间
   * </pre>
   *
   * <code>optional .Protocols.DateTime verifyTime = 3;</code>
   */
  boolean hasVerifyTime();
  /**
   * <pre>
   * 鉴定时间
   * </pre>
   *
   * <code>optional .Protocols.DateTime verifyTime = 3;</code>
   */
  com.dj.protobuf.datetime.DateTime getVerifyTime();
  /**
   * <pre>
   * 鉴定时间
   * </pre>
   *
   * <code>optional .Protocols.DateTime verifyTime = 3;</code>
   */
  com.dj.protobuf.datetime.DateTimeOrBuilder getVerifyTimeOrBuilder();

  /**
   * <pre>
   * 鉴定减少的时间(分钟)
   * </pre>
   *
   * <code>optional int32 verifyCD = 4;</code>
   */
  boolean hasVerifyCD();
  /**
   * <pre>
   * 鉴定减少的时间(分钟)
   * </pre>
   *
   * <code>optional int32 verifyCD = 4;</code>
   */
  int getVerifyCD();
}
