// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package com.dj.protobuf.test;

public interface TestReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protocols.TestReq)
    com.google.protobuf.MessageOrBuilder {
}
